### ISSUE TITLE
npc train function bug in latest build 393

### ISSUE THREAD

**Issue by WRWRs** [Sphereserver/Source#110]
if you try to train skills by NPC Vendor he says 65360 gold and i will train you... and skills train more than 30.0 (like in sphere.ini)
this bug only in latest builds, after dummies fix and skillsum :bye:

**Comment by WRWRs** [comment]
1st step you train to limit 
2nd you train more

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/a933c9b335ae23aafd19f0145ed0579808f21a95
