### ISSUE TITLE
npc trian skills to cap

### ISSUE THREAD

**Issue by WRWRs** [Sphereserver/Source#111]
NPCs offer to train and take money, but do not teach anything
But if you give them right summ of gold to npc. you can train to 30 and more

for example, i have veterinary skill = 1.7 if i want to train to 80. just need to give them 783gp
but he saying 2830 gp for train to 30.0
80 works for me cause my players have a limit on newbie island 80 for each skill

in sphere.ini
// Cost (in gp) of each 0.1 skill trained on NPCs
NPCTrainCost=10

and vendor says right money to train but learn when you give them other money Smile
if you give the more than 783 he just give your money

**Comment by coruja747** [comment]
are you using TAG.OVERRIDE.TRAINSKILLCOST or any other tag on the NPC?

**Comment by WRWRs** [comment]
Default scripts and latest sphere only
