### ISSUE TITLE
Crash Problem

### ISSUE THREAD

**Issue by tazmanyak** [Sphereserver/Source#112]
Hello,

I'm using 56b sources maybe more then 8 years and all the time I've been coding custom sphere server. Today, I decided to change platform toolset to (Visual Studio 2015) v140 (Win8.1 Release with definition of _WIN32_WINNT  = Win7). SphereServer is opening without any problem but when someone tries to login it just crashes. But in v100 (Win7 release), there is no problem. I'll be debugging when I have a time but maybe you may have faced the situation before.  Any Idea ? 

The error shown in WinServer 2012 R2 is BEX Error. As far as I know, it should be solved by some settings but which.

Thanks in advance,

Regards,

**Comment by coruja747** [comment]
Unfortunately I cant really help with 56b source since it really outdated and I never get a closer look at it, but afaik, the sphere automatic nightly compiler was using VS2010 to compile it, so try using Visual Studio 2010 to check if you can get better results
