### ISSUE TITLE
Interrupt cast bug

### ISSUE THREAD

**Issue by drk84** [Sphereserver/Source#117]
Even if your interrupt chance is 0 or the damage is set to dam_nodisturb, you will still fail to cast the spell because when you get hit you will always attempt to hit back (aborting the  magic action)

My solution was to add this in OnHarmedBy (CCharFight.cpp)
```
if (!g_Cfg.IsSkillFlag(Skill_GetActive(),SKF_MAGIC))
		Fight_Attack(pCharSrc);
```

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/7ad1ca913393b0d46b9018b1e7a808d5491890ae
