### ISSUE TITLE
StatCap problem

### ISSUE THREAD

**Issue by WRWRs** [Sphereserver/Source#121]
Chars can't reach stat cap maximum with 
`// Limits the MAXHITS/MAXMANA/MAXSTAM changes
// STAT_FLAG_NORMAL     00 // MAX* status allowed (default)
// STAT_FLAG_DENYMAX    01 // MAX* denied
// STAT_FLAG_DENYMAXP   02 //             .. for players
// STAT_FLAG_DENYMAXN   04 //             .. for npcs
StatsFlags=00`

For example STATSUM=300 and chars can train only 299 stats

**Comment by coruja747** [comment]
I merged this pull request on latest build, try using it to check if it got fixed

**Comment by WRWRs** [comment]
work fine now
