### ISSUE TITLE
INTERRUPT=0.0,0.0 has no effect on spells

### ISSUE THREAD

**Issue by MariusVendetta** [Sphereserver/Source#124]
If you put INTERRUPT=0.0,0.0 under a spell you still fizz if get hit by arrow and dagger (tested) other kind of weapon didn't test yet but most likely all of them.
For a better testing change a delay of a spell to 10 seconds so you have a much time to get hit.
(Las buid, last scripts)

**Comment by MariusVendetta** [comment]
actually seems that being hit causing @Abort witch cause aborting the spell

**Comment by coruja747** [comment]
try using the latest build to check if this got fixed

**Comment by MariusVendetta** [comment]
doawnloaded and compiled the new source under linux and i confirm it is not interrupting the spell if hitted
 and interrupt=0 and spell fizzles  if interrupt=100

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/7ad1ca913393b0d46b9018b1e7a808d5491890ae
