### ISSUE TITLE
Wrestling is very slow - DEX NON-DEPENDENT

### ISSUE THREAD

**Issue by MariusVendetta** [Sphereserver/Source#125]
clean sphere
clean scripts
2 new pg with dex 150 allskills 100.0
if empty handed  they attack each one every 26 secs aprox

just equiping a dagger it start hitting very fast (dex dependent)

**Comment by coruja747** [comment]
what CombatSpeedEra and SpeedScaleFactor values are you using on sphere.ini?

**Comment by MariusVendetta** [comment]
// Extra combat flags to control the fight (default:0, 0.55i compatible)
// COMBAT_NODIRCHANGE           00001 // Not rotate player when fighting
(like was in 0.51a)
// COMBAT_FACECOMBAT            00002 // Allow faced combat only
(recommended)
// COMBAT_PREHIT                00004 // Allow prehit for close combat.
first hit is instant (delay 0.1sec)
// COMBAT_ELEMENTAL_ENGINE      00008 // Use DAM*/RES* to split
damage/resist into Physical/Fire/Cold/Poison/Energy (AOS) instead use old
AR (pre-AOS)
// COMBAT_DCLICKSELF_UNMOUNTS   00020 // Unmount horse when dclicking self
while in warmode
// COMBAT_ALLOWHITFROMSHIP      00040 // Allow attacking opponents from
ships
// COMBAT_ARCHERYCANMOVE        00100 // Allow firing bow while moving
// COMBAT_STAYINRANGE           00200 // Abort attack swing when out of
range instead of waiting to come back in range
// COMBAT_STACKARMOR            01000 // If a region is covered by more
than one armor part, all AR will count
// COMBAT_NOPOISONHIT           02000 // Disables old (55i like) poisoning
style (0~100% chance based on Poisoning skill for monsters, or 50% chance
for poisoned weapons)
CombatFlags=01|020|0100

// Damage formula to use on physical combat
// 0 = Sphere custom
// 1 = pre-AOS
// 2 = AOS
CombatDamageEra=0

// Hit Chance formula to use on physical combat
// 0 = Sphere custom // Not compatible with Hit Chance Increase property
// 1 = pre-AOS // Not compatible with Hit Chance Increase property
// 2 = AOS
CombatHitChanceEra=0

// Swing Speed formula to use on physical combat
// 0 = Sphere custom // Recommended SpeedScaleFactor = 15000. Old Sphere
0.55 custom formula. Not compatible with Swing Speed Increase property, and
uses DEX instead STAM
// 1 = pre-AOS // Recommended SpeedScaleFactor = 15000. Not compatible with
Swing Speed Increase property
// 2 = AOS // Recommended SpeedScaleFactor = 40000
// 3 = SE // Recommended SpeedScaleFactor = 80000
// 4 = ML // Doesn't use SpeedScaleFactor. Only compatible with ML speed
format (eg. 0.25 ~ 5.00 seconds instead 0 ~ 50), uncomment
TAG.OVERRIDE.SPEED on all weapons to enable ML speed format
CombatSpeedEra=0

// Speed scale factor for weapons
SpeedScaleFactor=15000





Il 14 Mar 2018 05:27, "Coruja" <notifications@github.com> ha scritto:

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/45d05fb859cfb4dbcb66dad512c49fdfacf7da84
