### ISSUE TITLE
Can't equip items from pack when weight is on limit.

### ISSUE THREAD

**Issue by shiryux** [Sphereserver/Source#126]
CClient::Cmd_Use_Item checks if m_pChar->CanCarry(item).
So, if you have a sword in pack, and you're 410/412 in weight, you won't be able to equip it. If you drop it to the floor and equip it, you will be able.

Tweaked it like this:
CClientUse.cpp - Line 100
`			if (pItem->GetParent() != m_pChar->GetContainer(LAYER_PACK))
			{
				if (!m_pChar->CanCarry(pItem))
				{
					SysMessageDefault(DEFMSG_MSG_HEAVY);
					return false;
				}
			}`

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/62c00115a1d4ee39dbe29034b2a44e69822fff29

**Comment by shiryux** [comment]
Sorry.
Found this also replicates in CChar::CanCarry when trying to move items in the backpack.
