### ISSUE TITLE
PetsInheritNotoriety

### ISSUE THREAD

**Issue by shiryux** [Sphereserver/Source#127]
When you set to other than 0 it generates some debug errors in console:
I had it at PetsInheritNotoriety=01|02|04|08|010|020
Clicked the tamed char and this happened: (of course, name isn't displayed)

18:10:DEBUG:__ thread (8160) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
18:10:DEBUG:>>         8160     |  0 |                       CWorld::OnTick | +0 
18:10:DEBUG:>>         8160     |  1 |                      CSector::OnTick | +15 
18:10:DEBUG:>>         8160     |  2 |                        CChar::OnTick | +0 <-- exception catch point (below is guessed and could be incorrect!)
18:10:DEBUG:>>         8160     |  3 |            CChar::OnTickStatusUpdate | +0 
18:10:DEBUG:>>         8160     |  4 |                    CChar::UpdateMode | +0 
18:10:DEBUG:>>         8160     |  5 |                 CClient::addCharMove | +0 
18:10:DEBUG:>>         8160     |  6 |                 CClient::addCharMove | +0 
18:10:DEBUG:>>         8160     |  7 | PacketCharacterMove::PacketCharacterMove | +0 
18:10:DEBUG:>>         8160     |  8 |                  CChar::Noto_GetFlag | +0 
18:10:DEBUG:>>         8160     |  9 |                CChar::NotoSave_GetID | +0 
18:10:CRITICAL:Exception, in CChar::Tick() #5 "update stats"
18:10:DEBUG:__ thread (8160) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
18:10:DEBUG:>>         8160     |  0 |                 NetworkManager::tick | +0 
18:10:DEBUG:>>         8160     |  1 |                  NetworkThread::tick | +0 
18:10:DEBUG:>>         8160     |  2 |           NetworkInput::processInput | +0 
18:10:DEBUG:>>         8160     |  3 |            NetworkInput::processData | +0 
18:10:DEBUG:>>         8160     |  4 |            NetworkInput::processData | +0 
18:10:DEBUG:>>         8160     |  5 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
18:10:DEBUG:>>         8160     |  6 |         PacketSingleClick::onReceive | +0 
18:10:DEBUG:>>         8160     |  7 |           CClient::Event_SingleClick | +0 
18:10:DEBUG:>>         8160     |  8 |                 CClient::addCharName | +0 
18:10:DEBUG:>>         8160     |  9 |                   CChar::Noto_GetHue | +0 
18:10:DEBUG:>>         8160     | 10 |                  CChar::Noto_GetFlag | +0 
18:10:DEBUG:>>         8160     | 11 |                CChar::NotoSave_GetID | +0 
18:10:CRITICAL:Exception, in SUB: NetworkInput::Message::ProcessMessage()
18:10:DEBUG:1:Parsing Packet len=5 id=0x09 [2018/03/06 18:10:59]
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   09 00 00 44 fd                                    ...D.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/40763e749fb38fd42990a758ad9a1a879273c153
