### ISSUE TITLE
Dropping items in static tiles gets wrong Z

### ISSUE THREAD

**Issue by shiryux** [Sphereserver/Source#129]
Seems to be a bug with static items.
Try to drop items in Vesper entrance bridge or in Britain port. Anything with wooden planks and nothing below. The item gets a different Z than the static tile.

**Comment by MariusVendetta** [comment]
with client 7.0.23.1 and last sphere build this issue is not present.
also with last client 7.0.61.1 no problem

**Comment by coruja747** [comment]
do you remember the item id and region P coords where this occur?

and EF_ItemStacking is enabled on .ini?

**Comment by shiryux** [comment]
Happened with i_gold (500/5000 amount).
P = 2853,702,20
Also in 1440,1765,-2
EF_ItemStacking is NOT enabled.

**Comment by shiryux** [comment]
Close it. Client problem.
