### ISSUE TITLE
Cooking items

### ISSUE THREAD

**Issue by tonyuo** [Sphereserver/Source#132]
When i try to cook it said: "You can't really eat this". 
and i tried with an anvil and with fire created with kindling

[ITEMDEF 097a]
DEFNAME=i_fish_cut_raw
TYPE=t_meat_raw
TDATA1=i_fish_cut_cooked
VALUE=3
WEIGHT=0.1
SKILLMAKE=Cooking 10.0, t_cooking
CATEGORY=Provisions - Food
SUBSECTION=Meat
DESCRIPTION=Fish Steak (raw)

[ITEMDEF 0976]
DEFNAME=i_bacon_slab
TYPE=t_meat_raw
TDATA1=i_bacon_slice
//FIXME: A slab of raw bacon should make more than one slice.
FLIP=1
VALUE=25
WEIGHT=1.0
CATEGORY=Provisions - Food
SUBSECTION=Meat
DESCRIPTION=Slab of Bacon
DUPELIST=0977
ON=@Create
   MOREM=3

I tried with those 2 items (i didn't try with more cooking items)

**Comment by MariusVendetta** [comment]
Try, like the map bug, watch the type of uncooked and cooked and see if
after save or after setting correct type undet script it work. Maybe is a
bug caused by same problem. You should investigate better.

Il 18 Mar 2018 20:51, "tonyuo" <notifications@github.com> ha scritto:

**Comment by tonyuo** [comment]
I have been checking it.

t_meat_raw              135   // just a meaty part of a corpse. (uncooked meat)

If i use t_cooking, i can cook fish, but i can't cook bacon (for example) Among other

**Comment by coruja747** [comment]
instead click on the raw food, you must use an cooking tool (i_fry_pan, i_flour_sifter, i_rolling_pin) to open cooking skillmenu
