### ISSUE TITLE
Random disconnect on players

### ISSUE THREAD

**Issue by shiryux** [Sphereserver/Source#135]
Players get disconnected, but the char lingers (he doesn't show up in admin menu)
Char can't be killed, or if you kill it, it displays about 10 kill messages.

This is the debug when the player gets kicked.

> 02:53:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:53:DEBUG:>>         4564     |  0 |      NetworkManager::processAllInput | +0 
> 02:53:DEBUG:>>         4564     |  1 |           NetworkInput::processInput | +16 
> 02:53:DEBUG:>>         4564     |  2 |            NetworkInput::processData | +0 
> 02:53:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:53:DEBUG:>>         4564     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:53:DEBUG:>>         4564     |  5 |         PacketMovementReq::onReceive | +0 
> 02:53:DEBUG:>>         4564     |  6 |                  CClient::Event_Walk | +0 
> 02:53:DEBUG:>>         4564     |  7 |         CPartyDef::UpdateWaypointAll | +0 
> 02:53:CRITICAL:"Access Violation" (0x10aa43), in SUB: NetworkInput::Message::ProcessMessage()
> 02:53:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:53:43]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 05 05 00 00 00 00                              .......
> 02:53:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:53:DEBUG:>>         4564     |  0 |      NetworkManager::processAllInput | +0 
> 02:53:DEBUG:>>         4564     |  1 |           NetworkInput::processInput | +16 
> 02:53:DEBUG:>>         4564     |  2 |            NetworkInput::processData | +0 
> 02:53:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:53:DEBUG:>>         4564     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:53:DEBUG:>>         4564     |  5 |         PacketMovementReq::onReceive | +0 
> 02:53:DEBUG:>>         4564     |  6 |                  CClient::Event_Walk | +0 
> 02:53:DEBUG:>>         4564     |  7 |         CPartyDef::UpdateWaypointAll | +0 
> 02:53:CRITICAL:"Access Violation" (0x10aa43), in SUB: NetworkInput::Message::ProcessMessage()
> 02:53:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:53:44]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 06 07 00 00 00 00                              .......
> 02:54:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:54:DEBUG:>>         4564     |  0 |      NetworkManager::processAllInput | +0 
> 02:54:DEBUG:>>         4564     |  1 |           NetworkInput::processInput | +15 
> 02:54:DEBUG:>>         4564     |  2 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:54:DEBUG:>>         4564     |  5 |         PacketMovementReq::onReceive | +0 
> 02:54:DEBUG:>>         4564     |  6 |                  CClient::Event_Walk | +0 
> 02:54:DEBUG:>>         4564     |  7 |         CPartyDef::UpdateWaypointAll | +0 
> 02:54:CRITICAL:"Access Violation" (0x10aa43), in SUB: NetworkInput::Message::ProcessMessage()
> 02:54:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:54:27]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 86 11 00 00 00 00                              .......
> 02:54:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:54:DEBUG:>>         4564     |  0 |                 NetworkManager::tick | +0 
> 02:54:DEBUG:>>         4564     |  1 |                  NetworkThread::tick | +0 
> 02:54:DEBUG:>>         4564     |  2 |           NetworkInput::processInput | +0 
> 02:54:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  4 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  5 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:54:DEBUG:>>         4564     |  6 |         PacketMovementReq::onReceive | +0 
> 02:54:DEBUG:>>         4564     |  7 |                  CClient::Event_Walk | +0 
> 02:54:DEBUG:>>         4564     |  8 |         CPartyDef::UpdateWaypointAll | +0 
> 02:54:CRITICAL:"Access Violation" (0x10aa43), in SUB: NetworkInput::Message::ProcessMessage()
> 02:54:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:54:32]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 80 04 00 00 00 00                              ......
> 02:54:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:54:DEBUG:>>         4564     |  0 |      NetworkManager::processAllInput | +0 
> 02:54:DEBUG:>>         4564     |  1 |           NetworkInput::processInput | +16 
> 02:54:DEBUG:>>         4564     |  2 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:54:DEBUG:>>         4564     |  5 |         PacketMovementReq::onReceive | +0 
> 02:54:DEBUG:>>         4564     |  6 |                  CClient::Event_Walk | +0 
> 02:54:DEBUG:>>         4564     |  7 |         CPartyDef::UpdateWaypointAll | +0 
> 02:54:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:54:32]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 80 05 00 00 00 00                              ......
> 02:54:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:54:DEBUG:>>         4564     |  0 |      NetworkManager::processAllInput | +0 
> 02:54:DEBUG:>>         4564     |  1 |           NetworkInput::processInput | +16 
> 02:54:DEBUG:>>         4564     |  2 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:54:DEBUG:>>         4564     |  5 |         PacketMovementReq::onReceive | +0 
> 02:54:DEBUG:>>         4564     |  6 |                  CClient::Event_Walk | +0 
> 02:54:DEBUG:>>         4564     |  7 |         CPartyDef::UpdateWaypointAll | +0 
> 02:54:CRITICAL:"Access Violation" (0x10aa43), in SUB: NetworkInput::Message::ProcessMessage()
> 02:54:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:54:35]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 81 0a 00 00 00 00                              .......
> 02:54:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:54:DEBUG:>>         4564     |  0 |      NetworkManager::processAllInput | +0 
> 02:54:DEBUG:>>         4564     |  1 |           NetworkInput::processInput | +16 
> 02:54:DEBUG:>>         4564     |  2 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:54:DEBUG:>>         4564     |  5 |         PacketMovementReq::onReceive | +0 
> 02:54:DEBUG:>>         4564     |  6 |                  CClient::Event_Walk | +0 
> 02:54:DEBUG:>>         4564     |  7 |         CPartyDef::UpdateWaypointAll | +0 
> 02:54:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:54:35]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 81 0b 00 00 00 00                              .......
> 02:54:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:54:DEBUG:>>         4564     |  0 |      NetworkManager::processAllInput | +0 
> 02:54:DEBUG:>>         4564     |  1 |           NetworkInput::processInput | +16 
> 02:54:DEBUG:>>         4564     |  2 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:54:DEBUG:>>         4564     |  5 |         PacketMovementReq::onReceive | +0 
> 02:54:DEBUG:>>         4564     |  6 |                  CClient::Event_Walk | +0 
> 02:54:DEBUG:>>         4564     |  7 |         CPartyDef::UpdateWaypointAll | +0 
> 02:54:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:54:35]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 81 0c 00 00 00 00                              .......
> 02:54:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:54:DEBUG:>>         4564     |  0 |      NetworkManager::processAllInput | +0 
> 02:54:DEBUG:>>         4564     |  1 |           NetworkInput::processInput | +15 
> 02:54:DEBUG:>>         4564     |  2 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:54:DEBUG:>>         4564     |  5 |         PacketMovementReq::onReceive | +0 
> 02:54:DEBUG:>>         4564     |  6 |                  CClient::Event_Walk | +0 
> 02:54:DEBUG:>>         4564     |  7 |         CPartyDef::UpdateWaypointAll | +0 
> 02:54:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:54:35]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 81 0d 00 00 00 00                              .......
> 02:54:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:54:DEBUG:>>         4564     |  0 |      NetworkManager::processAllInput | +0 
> 02:54:DEBUG:>>         4564     |  1 |           NetworkInput::processInput | +16 
> 02:54:DEBUG:>>         4564     |  2 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:54:DEBUG:>>         4564     |  5 |         PacketMovementReq::onReceive | +0 
> 02:54:DEBUG:>>         4564     |  6 |                  CClient::Event_Walk | +0 
> 02:54:DEBUG:>>         4564     |  7 |         CPartyDef::UpdateWaypointAll | +0 
> 02:54:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:54:35]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 81 0e 00 00 00 00                              .......
> 02:54:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:54:DEBUG:>>         4564     |  0 |      NetworkManager::processAllInput | +0 
> 02:54:DEBUG:>>         4564     |  1 |           NetworkInput::processInput | +16 
> 02:54:DEBUG:>>         4564     |  2 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
> 02:54:DEBUG:>>         4564     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:54:DEBUG:>>         4564     |  5 |         PacketMovementReq::onReceive | +0 
> 02:54:DEBUG:>>         4564     |  6 |                  CClient::Event_Walk | +0 
> 02:54:DEBUG:>>         4564     |  7 |         CPartyDef::UpdateWaypointAll | +0 
> 02:54:DEBUG:f9:Parsing Packet len=7 id=0x02 [2018/03/31 02:54:35]
>         0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
>        -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
> 0000   02 81 0f 00 00 00 00                              .......
> 02:54:WARNING:f9:Disconnecting client from account 'leodagos' since it is causing exceptions problems
> 

After that I get several of these
02:54:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
02:54:DEBUG:>>         4564     |  0 |                       CWorld::OnTick | +0 
02:54:DEBUG:>>         4564     |  1 |                  CGObList::DeleteAll | +0 
02:54:DEBUG:>>         4564     |  2 |            CGObList::RemoveAtSpecial | +0 
02:54:DEBUG:>>         4564     |  3 |                 CGObList::OnRemoveOb | +0 
02:54:CRITICAL:"Access Violation" (0x109ce5), in Sphere::Tick() #3 "world"

When he tries to connect again:
02:55:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
02:55:DEBUG:>>         4564     |  0 |                 NetworkManager::tick | +0 
02:55:DEBUG:>>         4564     |  1 |                  NetworkThread::tick | +0 
02:55:DEBUG:>>         4564     |  2 |           NetworkInput::processInput | +0 
02:55:DEBUG:>>         4564     |  3 |            NetworkInput::processData | +0 
02:55:DEBUG:>>         4564     |  4 |            NetworkInput::processData | +0 
02:55:DEBUG:>>         4564     |  5 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
02:55:DEBUG:>>         4564     |  6 |            PacketCharPlay::onReceive | +0 
02:55:DEBUG:>>         4564     |  7 |                  CClient::Setup_Play | +0 
02:55:DEBUG:>>         4564     |  8 |                 CClient::Setup_Start | +0 
02:55:DEBUG:>>         4564     |  9 |              CClient::addPlayerStart | +0 
02:55:DEBUG:>>         4564     | 10 |              CClient::CharDisconnect | +0 
02:55:DEBUG:>>         4564     | 11 |                    CClient::Announce | +0 
02:55:DEBUG:>>         4564     | 12 |                    CGObList::GetHead | +0 
02:55:DEBUG:d:Parsing Packet len=73 id=0x5d [2018/03/31 02:55:01]
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   5d ed ed ed ed 4d 75 67  69 57 61 72 61 00 00 00   ]....MugiWara...
0010   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020   00 00 00 00 00 00 00 00  1f 00 00 00 00 00 00 00   ................
0030   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0040   00 00 00 00 00 c0 a8 00  05                        .........

And these repetitive messages when you kill him
03:20:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
03:20:DEBUG:>>         4564     |  0 |                       CWorld::OnTick | +0 
03:20:DEBUG:>>         4564     |  1 |                      CSector::OnTick | +0 
03:20:DEBUG:>>         4564     |  2 |                        CChar::OnTick | +0 <-- exception catch point (below is guessed and could be incorrect!)
03:20:DEBUG:>>         4564     |  3 |                         CChar::Death | +0 
03:20:DEBUG:>>         4564     |  4 |             CPartyDef::SysMessageAll | +16 
03:20:CRITICAL:"Access Violation" (0x10a943), in CChar::Tick() #2 "death"
03:20:ERROR:(sphere_guild_events.scp,43)Undefined keyword 'tag.override.noto'
03:20:P'MugiWara' was killed by N'Poisoner'
03:20:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
03:20:DEBUG:>>         4564     |  0 |                       CWorld::OnTick | +0 
03:20:DEBUG:>>         4564     |  1 |                      CSector::OnTick | +0 
03:20:DEBUG:>>         4564     |  2 |                        CChar::OnTick | +0 <-- exception catch point (below is guessed and could be incorrect!)
03:20:DEBUG:>>         4564     |  3 |                         CChar::Death | +0 
03:20:DEBUG:>>         4564     |  4 |             CPartyDef::SysMessageAll | +15 
03:20:P'MugiWara' was killed by N'Poisoner'
03:20:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
03:20:DEBUG:>>         4564     |  0 |                       CWorld::OnTick | +0 
03:20:DEBUG:>>         4564     |  1 |                      CSector::OnTick | +0 
03:20:DEBUG:>>         4564     |  2 |                        CChar::OnTick | +0 <-- exception catch point (below is guessed and could be incorrect!)
03:20:DEBUG:>>         4564     |  3 |                         CChar::Death | +0 
03:20:DEBUG:>>         4564     |  4 |             CPartyDef::SysMessageAll | +0 
03:20:P'MugiWara' was killed by N'Poisoner'
03:20:DEBUG:__ thread (4564) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
03:20:DEBUG:>>         4564     |  0 |                       CWorld::OnTick | +0 
03:20:DEBUG:>>         4564     |  1 |                      CSector::OnTick | +0 
03:20:DEBUG:>>         4564     |  2 |                        CChar::OnTick | +0 <-- exception catch point (below is guessed and could be incorrect!)
03:20:DEBUG:>>         4564     |  3 |                         CChar::Death | +0 
03:20:DEBUG:>>         4564     |  4 |             CPartyDef::SysMessageAll | +15 
03:20:CRITICAL:"Access Violation" (0x10a943), in CChar::Tick() #2 "death"
03:20:P'MugiWara' was killed by N'Poisoner'

**Comment by shiryux** [comment]
UpdateWaypointAll is being sent though we're using classic client (7.0.9.0)

**Comment by coruja747** [comment]
sounds weird, this map waypoint packet is only sent to enhanced clients

just to make sure, try type ".show ISCLIENTKR" and ".show ISCLIENTSA" to check if the server is considering your client as classic client instead enhanced client

**Comment by shiryux** [comment]
Returns 0 for me on all clients. This happens randomly, is the second player in a month.
The char shows online, and you can't kick him. Tried with .fix to apply FixWeirdness but nothing happened.
Solved by duping char and setting a different account for him.

**Comment by shiryux** [comment]
This happened for no reason yesterday:

19:27:e1:Client disconnected [Total:10] ('201.178.176.169', acct='Valighar')
19:27:DEBUG:__ thread (5084) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
19:27:DEBUG:>>         5084     |  0 |                       CWorld::OnTick | +0 
19:27:DEBUG:>>         5084     |  1 |                  CGObList::DeleteAll | +0 
19:27:DEBUG:>>         5084     |  2 |            CGObList::RemoveAtSpecial | +0 
19:27:DEBUG:>>         5084     |  3 |                 CGObList::OnRemoveOb | +0 
19:27:CRITICAL:"Access Violation" (0x109ce5), in Sphere::Tick() #3 "world"
19:28:ERROR:Undefined keyword 'disconnect'
19:28:DEBUG:__ thread (5084) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
19:28:DEBUG:>>         5084     |  0 |                       CWorld::OnTick | +0 
19:28:DEBUG:>>         5084     |  1 |        CTimedFunctionHandler::OnTick | +15 
19:28:DEBUG:>>         5084     |  2 |                        CChar::r_Verb | +0 <-- exception catch point (below is guessed and could be incorrect!)
19:28:DEBUG:>>         5084     |  3 |                     CClient::addKick | +0 
19:28:DEBUG:>>         5084     |  4 |                       CAccount::Kick | +0 
19:28:DEBUG:>>         5084     |  5 |             CResource::GetDefaultMsg | +0 
19:28:CRITICAL:Assert pri=2:'purecall' file 'unknown', line 1, in CChar::Verb()
