### ISSUE TITLE
Weights problem

### ISSUE THREAD

**Issue by WRWRs** [Sphereserver/Source#137]
in script: WEIGHT=15.5
in game 155 stones

**decimals not work** 
it was fine in 56b for example

in latest scripts with latest build i_robe weight=16.1 or 161 stones 😁

**Comment by MariusVendetta** [comment]
I can replicate this one.
```
[ITEMDEF 01b72]
DEFNAME=i_shield_round_bronze
NAME=round shield
TYPE=t_shield
//ARMOR=10
VALUE=48
WEIGHT=6.0
```
put to 6.4 work right. with more than one shield it sometimes show +6 or +7 is ok...
exec, on linux, built at 2018-04-20-16:18

**Comment by WRWRs** [comment]
looks like it's problem only latest WIN build

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/65d0fcc7b626cca247451c12b9cdd36429304167
