### ISSUE TITLE
error on TradeWindowSnooping option in sphere ini

### ISSUE THREAD

**Issue by merttumer** [Sphereserver/Source#138]
When its set to 0 the console gives this error when trying to open the backpack:

15:43:DEBUG: thread (14976)  |  # | __ function __ |  ticks passed from previous function start 
15:43:DEBUG:>>         14976     |  0 |      NetworkManager::processAllInput | +0 
15:43:DEBUG:>>         14976     |  1 |           NetworkInput::processInput | +16 
15:43:DEBUG:>>         14976     |  2 |            NetworkInput::processData | +0 
15:43:DEBUG:>>         14976     |  3 |            NetworkInput::processData | +0 
15:43:DEBUG:>>         14976     |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
15:43:DEBUG:>>         14976     |  5 |         PacketDoubleClick::onReceive | +0 
15:43:DEBUG:>>         14976     |  6 |           CClient::Event_DoubleClick | +0 
15:43:DEBUG:>>         14976     |  7 |                CClient::Cmd_Use_Item | +0 
15:43:DEBUG:>>         14976     |  8 |             CChar::Skill_Snoop_Check | +0 
15:43:DEBUG:>>         14976     |  9 |        CItemContainer::IsItemInTrade | +0 
15:43:DEBUG:1:Parsing Packet len=5 id=0x06 [2018/05/06 15:43:47]
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   06 40 00 1f 84

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/c575e1cd19313a9478fc899e164944d803e41ef3
