### ISSUE TITLE
Fishing results (fish) gets name of player

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source#139]
Fishing results (fish) gets name of player instead own names

**Comment by coruja747** [comment]
try check if your 'fishing_success' msg on sphere_msgs.scp is updated. I'm testing here and it seems to be working fine, the message is "You pull out a %s!" and when I get a fish it says "You pull out a fish!"

**Comment by WRWRs** [comment]
yeah...it say You pull out a fish but name of fish is player.name

**Comment by coruja747** [comment]
sounds weird, it's working fine here. Are you using any custom script or modded fishing skill on sphere_skills.scp?

**Comment by WRWRs** [comment]
using latest script pack

**Comment by WRWRs** [comment]
same problem with crafted items, they often shows names of other items in tooltip
