### ISSUE TITLE
Unused _DBPLUGIN

### ISSUE THREAD

**Issue by coruja747** [Sphereserver/Source#14]
Randomly taking a look at some source files, I found many "#ifdef _DBPLUGIN" with huge codes. But _DBPLUGIN is not defined and not used as preprocessor def

Honestly I don't know the purpose of this disabled code but it seems to be an old SQL engine not used anymore. So is it safe to remove it?

**Comment by Ben1028** [comment]
I think it can be removed.  You already removed the DBPlugin files some time ago :)

This was an attempt to have support for multiple database engine using a dll from what I can see.

**Comment by furio** [comment]
It was actually also a way to avoid tainting with possible GPL code since we were on a closed source basis :)
