### ISSUE TITLE
serv.account chang?

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source#141]
serv.log <serv.account.<account>.tag.email>
serv.account grammar invalidated?

**Comment by MariusVendetta** [comment]
You got 2 ..  ?


Il Mar 15 Mag 2018, 12:49 Breaker <notifications@github.com> ha scritto:

**Comment by Leodinas** [comment]
what?

**Comment by MariusVendetta** [comment]
serv.log <serv.account..tag.email>
Try
serv.log <serv.account.tag.email>

You got 2 dot  between serv.account and tag.email!

**Comment by Leodinas** [comment]
<serv.account.<account>.tag.email>

**Comment by MariusVendetta** [comment]
serv.log <serv.account..tag.email>
.....................................^.... need only one DOT

**Comment by Leodinas** [comment]
code is <serv.account.< account >.tag.email>
serv.account grammar invalidated?

**Comment by MariusVendetta** [comment]
code is <serv.account.< account >.tag.email>
.......................................^.............^......
Is this space really there?
Where you use that code?
Which trigger/function?
Is [] a player that actually has an account?

**Comment by Leodinas** [comment]
[function test]
serv.log <src.account.< account >.tag.email> // it not work
and test
[function test]
serv.log << account >.account.tag.email> // work

**Comment by azmanomer** [comment]
try
serv.log <src.account.tag0.email>
if the function used directly from player
serv.log <account.tag0.email>

**Comment by Leodinas** [comment]
ok

**Comment by MariusVendetta** [comment]
After some testing,
with last version
the "show serv.account.0" returns correct value if account exists or not.
the "show serv.account.0.whicheverproperty"  (name/password/tags/plevel/whatever) always returns 0 as value.

**which IS A BUG.**

problem is that you always had errors inside your question, which made your question stopping me before any other test...

**Comment by coruja747** [comment]
calling `ACCOUNT.x` functions directly on char seems to be working fine, but `SERV.ACCOUNT.x` is broken. I fixed it on latest build, so try update to this build to check if the problem still occur
