### ISSUE TITLE
Encryption Error

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#150]
I am encountering this error "(Encryption error (unknown encryption or bad login packet))" with initiatives with the customer.

**Comment by canavar2212** [comment]
I tried all the encryption options in the settings.

**Comment by coruja747** [comment]
what's the client version you're using?

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/e5d258b1efc2d7b63b6a7db53bede9efff9a0f89
