### ISSUE TITLE
CRITICAL:Exception, in CWorld::SaveTry()

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source#154]
Hi

do anyone knows, how to fix this bug or bad settings of sphere ?
background save settings - disabled
always when i tried to save sphere come out that debug and i cant do save anymore.
https://i.gyazo.com/96ef319bc2bc98be602ee4f426f30938.png
moving our server from 0.56b to 0.56d 2018 with saves and everything.

**Comment by coruja747** [comment]
what 56d build are you using? (you can get the value on first console line at server startup or using ".show serv.build")

**Comment by AtillaG1** [comment]
Build number 667.
Just some news, my collegue put in right saves and account and now we can save! But problem with error is still there, you can see on picture, but im not sure if you can help us with that. Maybe its just our bad settings or something ?? Thank you!
[![Screenshot from Gyazo](https://gyazo.com/b7999f71ca9548c7667f3dd74f2de3b2/raw)](https://gyazo.com/b7999f71ca9548c7667f3dd74f2de3b2)

**Comment by coruja747** [comment]
these "guard brain/timer" errors doesn't seems to be too serious, but errors on worldsave could delete the item/char with problem, so you should get some problems if something important (like an account char) get deleted

but anyway just to make sure, try update to latest build (currently it is 670) to check if this still happen. To update from build 667 to 670 you just need to replace sphereSvr.exe, sphere.ini and sphereCrypt.ini

**Comment by AtillaG1** [comment]
Oki
So i have now latest build 670.
After running sphere, some errors of items pop out, dont think its some major problem for us.
https://i.gyazo.com/1a45e1f103b596694441a9561cb175fc.png
After save, some of errors pop out but i think not that much. Also i think maybe few accounts gets error but im not sure. We are loading hundreds of accounts, so if 5 or 10 of them had problem, its still cool i guess.
https://i.gyazo.com/684032a66e2ae9593855c781089d6775.png

**Comment by AtillaG1** [comment]
Ok so now it looks like everything is OK. Thank you for your help! You are the man!
