### ISSUE TITLE
SYSMESSAGELOCEX function is not unavailable UNICODE text

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source#156]
Hello,

I tried to add the unicode character to this function, but the source code is associated with each function. you can add unicode usage to SYSMESSAGELOCEX function if possible?

Thank you.

**Comment by coruja747** [comment]
can you give an example? Because SYSMESSAGELOCEX is already unicode

**Comment by canavar2212** [comment]
This sysmessagelocex  function code;

SYSMESSAGELOCEX -1,<def.empty_cliloc>,00,abcçdefgğhıijklmnoöprsştuüvyzwxq,0

and for example ;
![unicode](https://user-images.githubusercontent.com/10347131/46765694-57a96b80-cce8-11e8-8f3b-bb11c9668f26.png)

**Comment by canavar2212** [comment]
I couldn't see these lines with the unicode of the corresponding function in the source code?

**Comment by coruja747** [comment]
I'm testing here and SYSMESSAGELOCEX is already unicode but it really replace some specific chars like this screenshot above. But using SYSMESSAGELOC (which uses ASCII instead unicode) it works fine

so probably the code is working fine, maybe these specific chars are ASCII instead unicode, so you just need to use SYSMESSAGELOC (ASCII) instead SYSMESSAGELOCEX (unicode)

**Comment by canavar2212** [comment]
All message functions except the SYSMESSAGELOCEX function with the client - server relationship and the packet data transponder client. However, in the use of SYSMESSAGELOCEX, the client does not get tired because there is no packet transfer. The opposite is the SYSMESSAGELOCEX ascii all other functions unicolor.

**Comment by canavar2212** [comment]
all message data types in the source code appear as follows.

```
case CHV_SMSG:
		case CHV_SMSGL:
		case CHV_SMSGLEX:
		case CHV_SMSGU:

		case CHV_SYSMESSAGE:
		case CHV_SYSMESSAGELOC:
		case CHV_SYSMESSAGELOCEX:
		case CHV_SYSMESSAGEUA:

```

burada sadece addBarkLocalizedEx fonksiyonuna unicode eklenmediği görülüyor.


```
	void addBark(LPCTSTR pszText, const CObjBaseTemplate *pSrc, HUE_TYPE wHue = HUE_DEFAULT, TALKMODE_TYPE mode = TALKMODE_SAY, FONT_TYPE font = FONT_BOLD);
	void addBarkUNICODE(const NCHAR *pszText, const CObjBaseTemplate *pSrc, HUE_TYPE wHue, TALKMODE_TYPE mode, FONT_TYPE font, CLanguageID lang = 0);
	void addBarkLocalized(DWORD dwClilocID, const CObjBaseTemplate *pSrc, HUE_TYPE wHue = HUE_DEFAULT, TALKMODE_TYPE mode = TALKMODE_SAY, FONT_TYPE font = FONT_BOLD, LPCTSTR pszArgs = NULL);
	void addBarkLocalizedEx(DWORD dwClilocID, const CObjBaseTemplate *pSrc, HUE_TYPE wHue = HUE_DEFAULT, TALKMODE_TYPE mode = TALKMODE_SAY, FONT_TYPE font = FONT_BOLD, AFFIX_TYPE affix = AFFIX_APPEND, LPCTSTR pszAffix = NULL, LPCTSTR pszArgs = NULL);
	void addBarkParse(LPCTSTR pszText, const CObjBaseTemplate *pSrc, HUE_TYPE wHue, TALKMODE_TYPE mode, FONT_TYPE font = FONT_NORMAL, bool fUnicode = false);
	void addSysMessage(LPCTSTR pszMsg);
	void addObjMessage(LPCTSTR pszMsg, const CObjBaseTemplate *pSrc, HUE_TYPE wHue = HUE_TEXT_DEF, TALKMODE_TYPE mode = TALKMODE_OBJ);
```
