### ISSUE TITLE
something strange with TIMERs 

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source#161]
have a great problem with timers or ticks i dont know
1. after restart sphere worldgembits gets big timers (for example 70000 instead real 180)
2. have an item healpad (regen stats by @STEP, usually it work looped but sometimes it work just 1 time when you step)
3. npc dont moving (like sleeped) before player interact them
4. today have a strange bug with Z parameter, player just drop down thru textures (dont changed any settings or files)
5. some items with t_eq_script id=i_memory not removed with firing TIMER and save on char with timer=0

check all of these on sourceX all work fine...

**Comment by coruja747** [comment]
yesterday I fixed an bug related to sphere startup not loading TIMER correctly on items/chars, so try update to the latest build to check if it's working fine

**Comment by Seokotov** [comment]
using X-source, i think it's work fine now
