### ISSUE TITLE
Ship move problem

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#162]
Char expansion = 08 // hs
Account.Resdisp = 08 // hs
Default script pack
Default sphere files
same as client and server files
Default High Seas muls
7x clients

ships are not going back and forward. problem apply to all ships (aos,ml & hs ships). Thank you.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/b9767756c2830d4787df8dce491e45174e846910

**Comment by canavar2212** [comment]
Thank you for your volunteer work.
