### ISSUE TITLE
USERSTATS trigger not working

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#167]
```
ON=@USERSTATS
SERV.LOG <NAME>
```

`12:18:(sphere_events_general.scp,9)UpdaterPP%M˜e ÿü
`
`12:16:DEBUG:command 'TRYSRC' args '0bc12%M˜e ÿü' [09F09260]`

Here are the bad characters. They're making sure the trigger doesn't work.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/c8c6397d6d92453d19f1793b24cc67a3a7b33177
