### ISSUE TITLE
MD5 Password Not Working

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#170]
// Store password hashed with MD5
Md5Passwords=1

When passwords are set to md5, sphere is turning md5 into password.

He gives this warning at every opening. Even if the passwords are md5; 

(sphereaccu.scp,9)Account 'test': plain text password converted to MD5 hash

it is already md5 is turning the password again md5.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/483bf385d81ee516327c48de68b5bcdbd76025c8
