### ISSUE TITLE
SAY on Linux Build

### ISSUE THREAD

**Issue by youhide** [Sphereserver/Source#171]
try speech (SAY) something on linux build... got a weird behavior
console prints only one char and on screen random
even we cant pass commands on char like .gm

![Screen Shot 2018-10-12 at 12 32 55](https://user-images.githubusercontent.com/4053124/57260886-ee01fd80-703b-11e9-9a54-7116d7c6e105.png)
![Screen Shot 2018-10-12 at 12 33 15](https://user-images.githubusercontent.com/4053124/57260890-f1958480-703b-11e9-9cdc-42f68da5b774.png)
![Screen Shot 2018-10-12 at 12 33 38](https://user-images.githubusercontent.com/4053124/57261346-cad84d80-703d-11e9-8bc7-77b217c88f94.png)

correct here is "hideOut"

![Screen Shot 2018-10-12 at 12 32 38](https://user-images.githubusercontent.com/4053124/57261002-68328200-703c-11e9-88a1-6c487fd9b31a.png)

**Comment by youhide** [comment]
![Screen Shot 2018-10-12 at 12 32 55](https://user-images.githubusercontent.com/4053124/57260886-ee01fd80-703b-11e9-9a54-7116d7c6e105.png)
![Screen Shot 2018-10-12 at 12 33 15](https://user-images.githubusercontent.com/4053124/57260890-f1958480-703b-11e9-9cdc-42f68da5b774.png)

**Comment by youhide** [comment]
correct here is "hideOut"

![Screen Shot 2018-10-12 at 12 32 38](https://user-images.githubusercontent.com/4053124/57261002-68328200-703c-11e9-88a1-6c487fd9b31a.png)

**Comment by youhide** [comment]
maybe because x64? 😅

**Comment by Fernandomr88** [comment]
![image](https://user-images.githubusercontent.com/14304128/57270970-e0f90480-7063-11e9-87a1-cf426154d08a.png)

all messed up

**Comment by coruja747** [comment]
usually these weird chars means incompatibility between 32/64bit arch

sphere is 32bit, so try check if your installed packages used by sphere are 32bit, and if you're compiling using gcc/cmake try check if "-march=i686 -m32" is set on compiler flags to force it build using 32bit

**Comment by youhide** [comment]
@coruja747 Im not compiling it, get it from sphere downloads page...
btw I try compiling it too... same behaviour.
😢

**Comment by Fernandomr88** [comment]
I compiled an older version from 2017 in the same computer, it worked. this last one didn't.
So I tried to download the compiled version from sphere website, same problem. No only speak but player name, gump text, all messed up.

**Comment by coruja747** [comment]
try using these builds to check if works
720: https://ci.appveyor.com/api/buildjobs/6f9r3nlnpxgsdgj5/artifacts/SphereSvr-Linux32.tar.gz
721: https://ci.appveyor.com/api/buildjobs/fb5x6eu9wxq7df16/artifacts/SphereSvr-Linux32.tar.gz

**Comment by youhide** [comment]
> try using these builds to check if works
> 720: https://ci.appveyor.com/api/buildjobs/6f9r3nlnpxgsdgj5/artifacts/SphereSvr-Linux32.tar.gz
> 721: https://ci.appveyor.com/api/buildjobs/fb5x6eu9wxq7df16/artifacts/SphereSvr-Linux32.tar.gz

same thing :(

**Comment by youhide** [comment]
this must be fixed my son

Lord British appreciate your help!

**Comment by coruja747** [comment]
Probably it's something related to your OS, I'm testing here on ubuntu 18 and it seems to be working fine. Try use these commands to make sure the system have full support to run 32bit apps
```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get dist-upgrade
```

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/fe0d8f63a872038b2cadc213b9dc937cf4ecf8fd

This was caused by wchar_t, for some unknown reason wchar_t works fine on some PC's but sometimes even this same PC running the same OS doesn't have proper wchar_t headers, and without wchar_t declared correctly sphere won't be able to parse correctly texts based on wide-chars. I just updated the WCHAR typedef from "wchar_t" to "unsigned short" which is a universal value compatible with any OS and now it seems to be working fine
