### ISSUE TITLE
Latest commit

### ISSUE THREAD

**Issue by Fernandomr88** [Sphereserver/Source#176]
Built https://github.com/Sphereserver/Source/commit/fdfed8a5c6ccdfbb92f80b43903d92de438fcba2 on Ubuntu 18.04 and when executing throws this error:

$ ./spheresvr
terminate called after throwing an instance of 'CGrayAssert'
Aborted (core dumped)

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/cd19da394f232338dbc504f9ae11aa80f5613bfd
