### ISSUE TITLE
Can't see ghost to dead players 

### ISSUE THREAD

**Issue by Pushim** [Sphereserver/Source#177]
UPDATE show the ghost if boot are in War Mode 
The patch:
ON=@UserWarmode
UPDATE
UPDATEX
RETURN 0

**Comment by canavar2212** [comment]
CharAct.cpp in ::Death() ;

		//StatFlag_Set(STATF_Insubstantial);
		//StatFlag_Clear(STATF_War);
		// Manifest the ghost War mode for ghosts. // 56b
		if (!IsStatFlag(STATF_War)) {
			StatFlag_Set(STATF_Insubstantial);
		}
		Update();		// show everyone I am now a ghost. // 56b

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/4012261685ee2e3d5aed2ec88a43dc0d3065b2fa
