### ISSUE TITLE
Party Bug

### ISSUE THREAD

**Issue by Pushim** [Sphereserver/Source#178]
When a player invite another to a "party" accept and disconnect from the server appear that console error and can't login to the server, the user stay in "Entering Britannia"

> ```
> 02:28:0:Client disconnected [Total:2] ('127.0.0.1', acct=admin')
> 02:28:DEBUG:__ thread (1788) __ | # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:28:DEBUG:>> 1788 | 0 | CWorld::OnTick | +0
> 02:28:DEBUG:>> 1788 | 1 | CGObList::DeleteAll | +32
> 02:28:DEBUG:>> 1788 | 2 | CGObList::RemoveAtSpecial | +109
> 02:28:DEBUG:>> 1788 | 3 | CGObList::OnRemoveOb | +0
> 02:28:CRITICAL:"Access Violation" (0x11eabf), in Sphere::Tick() #3 "world"
> 02:28:3:Client connected [Total:3] ('127.0.0.1' 1/3)
> 02:28:3:Login 'admin'
> 02:28:4:Client connected [Total:4] ('127.0.0.1' 1/4)
> 02:28:3:Client disconnected [Total:3] ('127.0.0.1', acct='admin')
> 02:28:4:Login 'admin'
> 02:28:4:Account 'admin' logged on char 'Cliff Burton' ('127.0.0.1')
> 02:28:DEBUG:__ thread (1788) __ | # | _____________ function _____________ | __ ticks passed from previous function start __
> 02:28:DEBUG:>> 1788 | 0 | NetworkManager::tick | +0
> 02:28:DEBUG:>> 1788 | 1 | NetworkThread::tick | +0
> 02:28:DEBUG:>> 1788 | 2 | NetworkInput::processInput | +0
> 02:28:DEBUG:>> 1788 | 3 | NetworkInput::processData | +0
> 02:28:DEBUG:>> 1788 | 4 | NetworkInput::processData | +0
> 02:28:DEBUG:>> 1788 | 5 | NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
> 02:28:DEBUG:>> 1788 | 6 | PacketCharPlay::onReceive | +0
> 02:28:DEBUG:>> 1788 | 7 | CClient::Setup_Play | +16
> 02:28:DEBUG:>> 1788 | 8 | CClient::Setup_Start | +0
> 02:28:DEBUG:>> 1788 | 9 | CClient::addPlayerStart | +0
> 02:28:DEBUG:>> 1788 | 10 | CClient::CharDisconnect | +0
> 02:28:DEBUG:>> 1788 | 11 | CClient::Announce | +0
> 02:28:DEBUG:>> 1788 | 12 | CGObList::GetHead | +0
> 02:28:CRITICAL:Assert pri=2:'purecall' file 'unknown', line 1, in SUB: NetworkInput::Message::ProcessMessage()
> 02:28:DEBUG:4:Parsing Packet len=73 id=0x5d [2019/05/14 02:28:25]
> 0 1 2 3 4 5 6 7 8 9 A B C D E F
> -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 0000 5d ed ed ed ed 43 6c 69 66 66 20 42 75 72 74 6f ]....Cliff Burto
> 0010 6e 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 n...............
> 0020 00 00 00 00 00 00 00 00 3f 00 00 00 00 00 00 00 ........?.......
> 0030 17 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
> 0040 00 00 00 00 00 c0 a8 00 11 .........
> ```

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/d09d1095767f3526fa710cf2addae6484a5873ad
