### ISSUE TITLE
Removing custom houses on Sphere using Linux causes Seg faults / crashes

### ISSUE THREAD

**Issue by s0ckz** [Sphereserver/Source#179]
m_pPacket below is not an array... Use delete instead... There are like 3 places to fix.

https://github.com/Sphereserver/Source/blob/master/src/graysvr/CItemMultiCustom.cpp#L41

**Comment by s0ckz** [comment]
@coruja747 please take a look here...

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/e29a5cf4eba3631c86560bf617e685f35805e287
