### ISSUE TITLE
Sphere.ini ClientVersion 

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#181]
'CLIENTVERSION' for 'MyShard' is '7.0.76.0'
Resync Start
Resync Re-Started.
Indexing 365 scripts...
Done loading scripts (112 of 200 triggers used)
Resync Complated

'CLIENTVERSION' for 'Player V Play' is '0.0.0'

After the server synchronizes, the server does not see the client version.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/6667496b59f001e1824cf7b0abce5eea2a76cda2

**Comment by canavar2212** [comment]
Thank you coruja.
