### ISSUE TITLE
Bank don't work correctly

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#183]
When adding item in the bank, the capacity of the bank do not change. You can put any quantity of weight you want.

When dclik on the bank. The msg say there is X Stones in the bank box. This number NEVER change....

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/2dca215a506dcad256b55119b46c7ebdc7cc07e1

**Comment by Nirad** [comment]
@coruja747 thx
