### ISSUE TITLE
SAY function

### ISSUE THREAD

**Issue by Khaldor48** [Sphereserver/Source#188]
.say function doesnt accept parameter @color etc... instead it print it along with text.. happening last two builds I guess

**Comment by Jhobean** [comment]
Just put this line before the .say
`.SPEECHCOLOR 00035`

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/ccb7a95a8df2f832ce5ae1bf020a0ca39aef5e50
