### ISSUE TITLE
SPAWN item

### ISSUE THREAD

**Issue by Khaldor48** [Sphereserver/Source#189]
SPAWN item doesn't change more2 value, when spawned creature is killed or removed. I just made quick workaround with @Destroy trigger, but it also doesn't fire everytime when npc is destroyed (for example when double clicking spawn item.. creature dissapears, but @Destroy trigger is not fired)

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/ccb7a95a8df2f832ce5ae1bf020a0ca39aef5e50

PS: MORE2 value is not used on worldgem bit anymore, to get the current spawned chars/items you must use COUNT
