### ISSUE TITLE
Protection spell does not raise armor rating

### ISSUE THREAD

**Issue by robertdeclaux** [Sphereserver/Source#19]
Not sure when it started to happen, just updated from 2012's. Tested with default script pack it doesn't seem to work on that too.

CombatFlags=0
CombatSpeedEra= 0
MagicFlags=0

Experimental=0
OptionFlags=020|0200|080

**Comment by coruja747** [comment]
Do you have COMBAT_ELEMENTAL_ENGINE enabled on sphere.ini?
The protection spell can have 2 different behaviors, it only uses the old AR if you have COMBAT_ELEMENTAL_ENGINE disabled

**Comment by robertdeclaux** [comment]
CombatFlags=0, it's not enabled but still we dont get old ar value.
Also COMBAT_PREHIT is disabled but it still first hit is instant.

Another question:
I was using 03 May 2011 nightly release, SpeedScaleFactor was 15000.
Now i set CombatSpeedEra= 0, and SpeedScaleFactor=15000 but weapon speeds are much faster than it was, what would you suggest?

**Comment by coruja747** [comment]
I think I found the problem. The protection AR bonus is not being added directly to the char AR, it just apply the bonus on ARMOR value of all equipped items on the char. In other words: if the char is not wearing any armor, the bonus will be 0. On next nightly build I will change it to apply the bonus directly on char AR, this will fix this problem

and if you're using CombatSpeedEra=0 with the same SpeedScaleFactor as you're using before, you already have the same old formula from old sphere builds. On newest builds the animation is faster, but the total swing delay is the same. Using for example an attack with 2.0 swing delay:
-on old builds the attack animation will be slower and the hit will occour only at timer end (2.0s)
-on newest builds the hit always occour at 0.7s, and them the char keep waiting the remaining time (1.3s) until next swing

so visually the attack seems to be faster, but both styles have the same 2.0s delay. You can customize these values on @HitTry using ARGN1 (swing delay) and LOCAL.AnimDelay. You can make the animation slower as before, just change the animation length to be the same as the total swing delay:
ON=@HitTry
LOCAL.AnimDelay=<ARGN1>

**Comment by robertdeclaux** [comment]
Fixed by coruja747 d79ba309e485aed16d74970024f0fdb422e7a17f
