### ISSUE TITLE
Can't login on Linux build

### ISSUE THREAD

**Issue by youhide** [Sphereserver/Source#193]
When i try to login with linux build all accounts are getting account already used...

**Comment by Jhobean** [comment]
I have the same problem on Windows but it's interminent

**Comment by youhide** [comment]
> I have the same problem on Windows but it's interminent

last windows build is ok here

**Comment by coruja747** [comment]
I compiled an test build with some extra debug info on the "account already in use" msg, try using it and check the console log
https://ci.appveyor.com/api/buildjobs/cu1evclhk1qov3l4/artifacts/SphereSvr-Linux32-Test.tar.gz

**Comment by youhide** [comment]
> I compiled an test build with some extra debug info on the "account already in use" msg, try using it and check the console log
> https://ci.appveyor.com/api/buildjobs/cu1evclhk1qov3l4/artifacts/SphereSvr-Linux32-Test.tar.gz

same...
![Capture](https://user-images.githubusercontent.com/4053124/64654356-61a78300-d3ff-11e9-8475-c20f8deecaf5.PNG)

**Comment by coruja747** [comment]
Do you have an custom IP set on [SPHERE] or [SERVERS] template on sphere.ini?

It seems that your client is connecting with IP 10.0.0.175 and after this it turns into 189.*.*.*

**Comment by youhide** [comment]
just ServIP on ini.
this is because i'm using lan address to connect on client-side and on server the .ini conf ServIP is pointing to external.
maybe sphere login steps act like a proxy?

**Comment by coruja747** [comment]
not really a proxy, it's just an simple gateway. Sphere have it's own IP and a [SERVERS] list with many IPs of others servers to show on server selection screen. After select an server on list, the client will drop the current connection and connect on selected IP. If the client select the own server it will connect again on same server, and if it click on another server IP it will be redirected to this other server IP

And probably your network settings are making the client make the 1st connection using local IP and 2nd connection using external IP, which will be a different IP so sphere will think that another IP is trying to use the same account

Honestly I have no idea why it occur, I'm trying to test it but both win/linux builds are working fine here. But anyway try set ServIP=127.0.0.1 and enable RestAPIPublicIP to check if it works

**Comment by Jhobean** [comment]
We had a @login with a return 1 on it. The return 1 was sometime causing this bug.

**Comment by youhide** [comment]
if put a wrong password and try to login again with correct im getting this on console and cant login...

22:40:FATAL:Segmentation fault
22:40:FATAL:Error Pri=1, Code=11, Desc='Segmentation fault', in NetworkInput::ProcessNewClient() #1 "messages  - setup"

**Comment by coruja747** [comment]
Maybe this is related to #195
I have no idea why sometimes linux builds was making the client change its IP without any reason, but since the login behavior is working fine on latest builds I think its safe consider this issue fixed
