### ISSUE TITLE
Dupelist not working on forge

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#194]
These 2 items of script pack do not work when i want to change their shape.

ITEMDEF 0197a]
DEFNAME=i_forge_large_bellows

[ITEMDEF 0197e]
DEFNAME=i_forge_large

When I drop them down, they always keep the same shape.....

It's normal?
Thx

**Comment by coruja747** [comment]
It's working fine, this item have "impassable / not movable" flag set directly on UO tiledata file, and by default sphere can only flip movable items

So if you really want force this item to flip you must set ATTR "attr_move_always" on it (note that "attr_move_always" will make it movable even to players). The same occur if you set "attr_move_never", this will turn an "movable" item into "not movable" and will make it not flip

**Comment by Jhobean** [comment]
Thx! @coruja
