### ISSUE TITLE
Corpse hardcoded @Click

### ISSUE THREAD

**Issue by Khaldor48** [Sphereserver/Source#197]
Corpses doesn't show count of items and stones as it did before few builds. 
![image](https://user-images.githubusercontent.com/22933400/65066205-3c2cf300-d984-11e9-88e5-3c5008963fb9.png)

I created my own @Click trigger message to show counter

**Comment by coruja747** [comment]
It's working fine, the code is intended to not show this info when click on corpses. This is required to make the old "click" (clients with tooltip disabled) show the same info of clients using tooltips (where the tooltip also don't show this info on corpses)
https://github.com/Sphereserver/Source/blob/55a0b99cf755b5709f39c02a11294a3082bb5b1d/src/graysvr/CClientMsg.cpp#L1169

But anyway if you like to show it again I recommend use an custom script like this
```
[TYPEDEF t_corpse]
ON=@AfterClick
LOCAL.ClickMsgText .= " (<COUNT> items, <WEIGHT> stones)"
```

**Comment by Khaldor48** [comment]
Thank you for clarification.
