### ISSUE TITLE
Using Board when crafting board

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#199]
When crafting an I_board, the caracter use the i_board in our backpack....

So it's impossible to easily make a stock of board.
I thought of 2 Solutions:
1- Modify the list like Coruja explain in the forum post
2- When crafting a Board, Use ALL the Logs in inventory and craft the same QTY of Board.

All info is on this post:
https://forum.spherecommunity.net/Thread-Crafting-with-board-or-log?action=newpost

**Comment by Khaldor48** [comment]
there is setting for this in sphere.ini
```
// EF_Item_Strict_Comparison	00000040 // Don't consider log/board and leather/hide as the same resource type
```
just set
```
Experimental=00000040 
```

**Comment by Jhobean** [comment]
Good to know thx. But i want to use board as log.

**Comment by coruja747** [comment]
Items are placed on containers following an order, last item placed is always at the end. So using as example an backpack with 3 items inside (spellbook, saw, log) the initial order will be something like this:
1) 1 spellbook
2) 1 saw
3) 100 log

All container loop-based functions (craft skills, FORCONT, FINDCONT.x, etc) will search for items inside this container following this order, and new items dropped inside this container are always placed at the end

I'm testing here crafting some boards on an empty server (latest 56d build + latest script pack) and got this result:
1) 1 spellbook
2) 1 saw
3) 99 log
4) 1 board

Note that the new item (board) got placed at the end, and log (3) still located before board (4) so the next craft will consume the log instead the board, which seems to be working fine:
1) 1 spellbook
2) 1 saw
3) 98 log
4) 2 board

After craft many boards I'm still getting the correct result:
1) 1 spellbook
2) 1 saw
3) 70 log
4) 30 board

So honestly I don't know why it's not working on your server. I'm taking a look at the internal code and it seems to be working fine. Try check if you have any custom trigger on char / backpack / craft skills (or custom craft functions) which is causing some kind of conflict with sphere internal behavior

**Comment by Jhobean** [comment]
Woaa thx for this clear explanation and time for the test. If I resume, DONT move log... now after all these explication, i'll test.

**Comment by Jhobean** [comment]
Just maked some test...  It's seem that my client make the loop inverse....

1- First crafting, I use the log
2- Second crafting, I use the board
3- Infinite using of board
......

Between step 1 and 2, If I move the log in my pack, its work..  So after each board, I must move my log. 

Knowing that i'm able to craft board. It's not optimal but working. If you don't have other idea, i'll close the issues.

I'll whait your answer.

A big thx for your help and all your time!
