### ISSUE TITLE
Walking forever

### ISSUE THREAD

**Issue by robertdeclaux** [Sphereserver/Source#20]
https://www.youtube.com/watch?v=mooEA-sR044

Not sure when it started to happen, just updated from 03 May 2011 nightly release.

CombatFlags=0
CombatSpeedEra= 0
MagicFlags=0

Experimental=0
OptionFlags=020|0200|080

**Comment by coruja747** [comment]
try using this debug test:
-add this line on sphere.ini: PACKET2=f_walk_test
-add this function on any script:

[FUNCTION f_walk_test]
REF1=<LOCAL.CHAR>
REF1.SYSMESSAGE <dLOCAL.2>

this will make your client show a sysmessage with a number everytime you move. When it reach 254 it goes back to 0, so check if this problem occour exactly at this moment when it reach 254

**Comment by coruja747** [comment]
also try using the latest nightly, maybe the last commit https://github.com/Sphereserver/Source/commit/140866267e4591c1d4cdad7f85096f1e9a6bf9b6 can fix this problem

**Comment by robertdeclaux** [comment]
Fixed by @coruja747
