### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by FiLoUs64** [Sphereserver/Source#201]
![image](https://user-images.githubusercontent.com/47130805/66725836-4adfbc00-ee03-11e9-9a08-704bdcbbdf87.png)

Hi

still the same problem when login... Thanks

**Comment by canavar2212** [comment]
I have the same error.

**Comment by Jhobean** [comment]
If you have a test build again. We will try it again.

**Comment by coruja747** [comment]
Try using latest build to check if this error still occur

**Comment by canavar2212** [comment]
error persists.

**Comment by canavar2212** [comment]
the first login to the game is successful, then offline, and we try to get back online gives this error
