### ISSUE TITLE
Encryption error login

### ISSUE THREAD

**Issue by canavar2212** [Sphereserver/Source#204]
```
14:00:0:Client connected [Total:1] ('212.2.212.116' 1/1)
14:00:0:Login 'xxx'
14:00:0:Client disconnected [Total:0] ('212.2.212.116', acct='xxx')
14:00:1:Client connected [Total:1] ('212.2.212.116' 1/2)
14:00:WARNING:1:Bad Login 11 (Encryption error (unknown encryption or bad login packet))
14:00:1:Client disconnected [Total:0] ('212.2.212.116', acct='<NA>')
```

Last version login error.

Sphere V0.56d-Nightly (32 bits) by www.spherecommunity.net
Compiled at Oct 19 2019 (build 936 / Git hash 909cdeff)

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/a7a34afaff2a03a7a78df68f2b566d5c7b381baf

**Comment by canavar2212** [comment]
this problem is still going on for 2.0.3 client

**Comment by coruja747** [comment]
Try using latest build to check if its working fine now
