### ISSUE TITLE
CRITICAL:"Access Violation" (0xff994ffe)

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#206]
Since 1 week, we have this bug. It's intermitent...

Seem to appear after the sphere_serv_triggers

The console is flooded by CRITICAL:"Access Violation". The server no more respond and the size of sphereworld.scp climb up to more than 1 GO...

Any Idea where to look at first? Script? , Save? Core? 

THX!!

```
22:34:(sphere_serv_triggers.scp,194)Statics data saved (save/spherestatics.scp)
22:34:ERROR:UID=040156ac7, id=0be9 'Sorcerers' Guild', Invalid code=2236 (Item flagged as decay but without timer set)
22:34:ERROR:UID=0401578f3, id=0be9 'Sorcerers' Guild', Invalid code=2236 (Item flagged as decay but without timer set)
22:34:GC: 339329 objects accounted for
22:34:CRITICAL:"Access Violation" (0xff994ffe), in Write Object 05b39cb8
22:34:CRITICAL:"Access Violation" (0xff994ffe), in Write Object 05b39cb8
22:34:CRITICAL:"Access Violation" (0xff994ffe), in Write Object 05b39cb8
22:34:CRITICAL:"Access Violation" (0xff994ffe), in Write Object 05b39cb8
22:34:CRITICAL:"Access Violation" (0xff994ffe), in Write Object 05b39cb8
22:34:CRITICAL:"Access Violation" (0xff994ffe), in Write Object 05b39cb8
```

**Comment by FiLoUs64** [comment]
Same server as @Jhobean 

I got this error this morning. The save was not big as the other day but is corrupt.

![image](https://user-images.githubusercontent.com/47130805/67635061-f0317000-f898-11e9-9fcd-b10e46b7c102.png)

**Comment by coruja747** [comment]
This UID 05b39cb8 is making sphere return error when try to write it on save file, so try search for "SERIAL=05b39cb8" on previous save file to check if there's something wrong on this UID

**Comment by FiLoUs64** [comment]
I've checked all my save from oct 16 to oct 27 and this serial does not appear.

The only thing that I noticed is that I did not launch sphere in administrator mode. So maybe it's the problem. Will keep you inform.
