### ISSUE TITLE
t_multi and item inside of it

### ISSUE THREAD

**Issue by Nirad** [Sphereserver/Source#207]
Item are not send to the client until you enter in the region of the multi if you can point me where to start to fix this thx!

![Capture d’écran 2019-10-29 à 15 47 22](https://user-images.githubusercontent.com/359353/67803518-97fa9980-fa63-11e9-9414-87bd3809ead7.png)

![Capture d’écran 2019-10-29 à 15 47 54](https://user-images.githubusercontent.com/359353/67803522-99c45d00-fa63-11e9-9e28-349f7d6cf8e3.png)

**Comment by Nirad** [comment]
![multi bug-2](https://user-images.githubusercontent.com/359353/67806840-10fcef80-fa6a-11e9-97a1-6a8dc4235640.gif)

**Comment by coruja747** [comment]
This is the OF_OSIMultiSight feature (sphere.ini) to avoid send useless packets when clients are running around houses with tons of itens, so to make sphere always send items inside multis you can just disable this feature

PS: clients >= 7.0.76.46 also have a new feature "Display house content" on options menu to toggle on/off this feature only for this client, so if your server use this client you can leave OF_OSIMultiSight enabled and let ppl leave this feature on/off using client options menu

**Comment by Nirad** [comment]
oh is that simple.... I will try that and close after thx !

**Comment by Nirad** [comment]
Arf thx I will check ini first next time ...

![Capture d’écran 2019-10-29 à 17 10 44](https://user-images.githubusercontent.com/359353/67809449-1577d700-fa6f-11e9-9585-c5f743a49018.png)
