### ISSUE TITLE
maxhits, maxstam, maxmana issues

### ISSUE THREAD

**Issue by Dragorniak** [Sphereserver/Source#210]
The problem appears when you set via script or manually the maxhits, maxstam or maxmana value. Then, when you cast bless or another spell on the character edited, the str, dex and int will change but the maxhits, maxstam and maxmana will not change automatically.

**Comment by Jhobean** [comment]
I think The maxhits do not follow the str anymore... If you want raise str AND maxhits, you must modifie the spell.

**Comment by Dragorniak** [comment]
when i don't modify the maxhits, it works like it should work, the problem is when i touch them, they become in some sort of manual operation.

**Comment by Jhobean** [comment]
Hahaha. Its funny because yeaterday i notified the same thing! What I did, i made at first login maxhits = str
Until this time, the hits di not follow str anymore.  But maybe Coruja will explain if its normal.

**Comment by Jhobean** [comment]
My théorie is if you dont have maxstats set on the player, the core use the old method to determine mana, stam,hits. As soon you define a maxstat, the core change the calculation.

**Comment by Khaldor48** [comment]
You can disable these max attributes in sphere.ini and therefore you'll have hits = str etc..

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/bf5cce5f10206c979d1b4478dea0c51ca8b1f8da
