### ISSUE TITLE
Search function in .add menu

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#211]
Since the update of SQL librairy, the search function in the .add menu seem to not work anymore.

**Comment by coruja747** [comment]
Is there any specific instructions to reproduce this bug? I'm testing here on latest build and it seems to be working fine

**Comment by Jhobean** [comment]
Ok i'll reproducen and show you. This week.

**Comment by Jhobean** [comment]
I think its after rebuilding the db with the function.  I'll do More test later

**Comment by Jhobean** [comment]
Update core and seem to work.... Don't know why it was bugging... THX for testing! And sorry.
