### ISSUE TITLE
Items in houses disappear 

### ISSUE THREAD

**Issue by FiLoUs64** [Sphereserver/Source#213]
We have a problem since a couple of day, randomly the item in house disappear. They are not decay but we see the house with nothing inside , no door, no sign no items. We think when it's come to day time we have the problem, never during night time. 

![](https://media.discordapp.net/attachments/579309906532761630/645820731736719400/unknown.png)

![](https://media.discordapp.net/attachments/579309906532761630/645821028525670410/unknown.png)

Thanks for your help

**Comment by coruja747** [comment]
It still happening on latest build?

**Comment by FiLoUs64** [comment]
Everythings good. Thanks
