### ISSUE TITLE
Strange BUG in String syntax

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#214]
I have this code in my script...

In 56d the resuslt is 0

In X, the result is 500 

I need to have an answer of 500...  Any idea what looking for?

```
[DEFNAME achievement_def]

achievement_1_1_palier20 = 500


[FUNCTION test]
src.clearctags
src.ctag0.achievement_1_1_palier = 20
src.sysmessage <eval <DEF.achievement_1_1_palier<src.ctag0.achievement_1_1_palier>>>
```

**Comment by Khaldor48** [comment]
This is happening because <src.ctag0.achievement_1_1_palier> is returning 014 (hex), so script is looking for achievement_1_1_palier014 

all you need to do is retuning ctag in decimal value ... this will do the trick
```
src.sysmessage <eval <DEF.achievement_1_1_palier<dsrc.ctag0.achievement_1_1_palier>>>
```

**Comment by Jhobean** [comment]
THX!!! Working!!
