### ISSUE TITLE
 HITS goes back to STR value when it takes any HIT

### ISSUE THREAD

**Issue by dicataldisky** [Sphereserver/Source#219]
If the STR is 120 for exemple and char hits is 200, if it takes any damage the HIT drops 
instantly to 120.

Is there any flag to remove this? If there is no flag, could you tell me where to find it in the code to disable the feature?

**Comment by Jhobean** [comment]
I think Your maxhits is not set. If you want increase your hits
Maxhits =200
Hits =200

**Comment by dicataldisky** [comment]
the problem is not to increase maxhits, an issue that occurs when the value changes, either str, dex or int automatically, or the maxhits value is equal to str

**Comment by coruja747** [comment]
Probably you're confusing STR, HITS and MAXHITS

STR is not the same thing as MAXHITS, and HITS can never be > MAXHITS (when sphere detect that HITS > MAXHITS it will automatically fix this setting HITS = MAXHITS)

If MAXHITS value is empty, sphere will inherit its value from STR, so if you set STR=120 it will also set MAXHITS=120. And since the max value is 120, the HITS max value will also be limited to 120

To avoid this you must set STR=200 (which will also set MAXHITS=200 automatically), or keep STR=120 and set MAXHITS=200

**Comment by Jhobean** [comment]
And if you want change the str, change modstr.

**Comment by dicataldisky** [comment]
I don't think I can explain myself properly because of my English,

what I need is to be able to disable the feature that makes sphere automatically fix this setting HITS = MAXHITS)

I'm thinking of compiling the sphere here on my machine with this change ... can you tell me exactly the file and the linahs that I should change? does the build version of sphere work in visual studio 2019? thankful!

**Comment by Jhobean** [comment]
I understand your need. We had the exact same problem 3 week ago. What we did is adapt our script with maxhits and modstr. Now it's done, we have more functionnality.
For the modification of the core, I have no idea...

**Comment by dicataldisky** [comment]
Okay, could you show me 1 item that you use to follow an example?

**Comment by Jhobean** [comment]
```
ON=@EQUIP
HITPOINTS=32700
SRC.EVENTS +e_aventurier_xbow
SRC.MODDEX=<SRC.MODDEX>+10
SRC.STAM=<SRC.STAM>+10
SRC.MAXSTAM=<SRC.MAXSTAM>+10
```

**Comment by dicataldisky** [comment]
I think that independent should need to modify the core, but even following your example after removing or adding the item hits and is set by the value of str

`ON=@EQUIP
	
	SRC.MODSTR=<SRC.MODSTR>+10
	SRC.HITS=<SRC.HITS>+10
	SRC.MAXHITS=<SRC.MAXHITS>+10


	SRC.MODDEX=<SRC.MODDEX>+5
	SRC.STAM=<SRC.STAM>+5
	SRC.MAXSTAM=<SRC.MAXSTAM>+5

ON=@UNEQUIP
	SRC.MODSTR=<SRC.MODSTR>-10
	SRC.HITS=<SRC.HITS>-10
	SRC.MAXHITS=<SRC.MAXHITS>-10

	SRC.MODDEX=<SRC.MODDEX>-5
	SRC.STAM=<SRC.STAM>-5
	SRC.MAXSTAM=<SRC.MAXSTAM>-5`

**Comment by FiLoUs64** [comment]
You can disable MAXHITS, MAXSTAM and MAXMANA in sphere.ini

> // Limits the MAXHITS/MAXMANA/MAXSTAM changes
// STAT_FLAG_NORMAL		00 // MAX* status allowed (default)
// STAT_FLAG_DENYMAX		01 // MAX* denied
// STAT_FLAG_DENYMAXP		02 //             .. for players
// STAT_FLAG_DENYMAXN		04 //             .. for npcs
StatsFlags=00

**Comment by Jhobean** [comment]
Since you will have a value in maxhits, the hits will not follow str anymore.

What we did was initialize the maxhits in the first login.

Remove all item
Modstr=0
Str=100
Maxhits=<str>

After that you only modifs modstr and maxhits

**Comment by dicataldisky** [comment]
@coruja747 
sorry to disturb you +1 time with this, I ran a custom version to solve my problem, it worked fine, now I'm just trying to find where hits goes down to str when it takes any punch .. can you tell me where I find it inside CCharSkill.cpp ? and which line should I change? thanks!

**Comment by coruja747** [comment]
When MAXHITS is not set, it will automatically inherit the value from STR, so STR=100 will also make MAXHITS=100, and this is working fine

If MAXHITS is set to any other value it will "unlink" from STR, so you can set different values like STR=100 and MAXHITS=110, which is also working fine

But I did some tests and this really seems to be affecting spells. If you have STR=100 and set MAXHITS=110, this will make MAXHITS unlink from STR as expected, but this will also break status spells (like strength, etc) making the spell only change STR but not MAXHITS. I must do some deep testing to check what can be done here, but probably the best fix is make spells change both status (eg: STR + MAXHITS instead only STR)

**Comment by dicataldisky** [comment]
Can't you talk to me in Portuguese privately to explain me better? I'm 5 days trying to solve this lol

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/bf5cce5f10206c979d1b4478dea0c51ca8b1f8da
