### ISSUE TITLE
Archery weapon's speed can't set and it's really quick with combatflags 0

### ISSUE THREAD

**Issue by robertdeclaux** [Sphereserver/Source#22]
Even if i change weapon's weight, speed or char's dex it does not effect on speed. I can't get it slower it hits one in one sec.

SpeedScaleFactor=15000
CombatFlags=0
CombatSpeedEra= 0
MagicFlags=0

Experimental=0
OptionFlags=020|0200|080

**Comment by coruja747** [comment]
just remove the DELAY line on Skill_Archery (sphere_skills.scp) and restart the server, this will fix this problem. I already had fixed this problem some days ago but forgot to commit this change :P

**Comment by robertdeclaux** [comment]
:+1:
