### ISSUE TITLE
 NPCs equips objects when they do not have the mt_equip flag

### ISSUE THREAD

**Issue by FiLoUs64** [Sphereserver/Source#222]
NPCs equips object for example weapon or shield even if they don't have the MT_EQUIP flags.

Checked the change log and this was fixed in 56b but seems to have a problem in 56d.

> 14-09-2005, Vjaka
- Fixed: NPC item equipping not having mt_equip flag.

**Comment by coruja747** [comment]
I don't remember exactly but I think MT_EQUIP flag only check armors, to check items equipped on hands it uses MT_USEHANDS instead MT_EQUIP
