### ISSUE TITLE
char does not leave frozen after paralyze field ends

### ISSUE THREAD

**Issue by dicataldisky** [Sphereserver/Source#223]
a char q gets stuck in the paralyze field even after its ending is frozen until someone dispels .. I believe the correct attitude would be after the disappearance of the field that is in your foot start the normal paralyze timer ..

**Comment by Khaldor48** [comment]
Current behavior is OK. You ask something which you can do via script.
just add this code to paralyze field :

```
on=@Destroy // (or @Timer)
forchars 0
    if (<flags>& statf_freeze)
        flags = <flags>&~ statf_freeze
    endif
endfor
```

**Comment by coruja747** [comment]
This already got fixed some years ago
https://github.com/Sphereserver/Source/blob/bf5cce5f10206c979d1b4478dea0c51ca8b1f8da/src/graysvr/CCharSpell.cpp#L615

Maybe this should be related to an custom client version not receiving this "update" packet or some custom script conflicting with sphere default spell behavior

**Comment by Khaldor48** [comment]
I guess he means that char stepped into paralyze field then paralyze field disapears and then the character is still frozen because he has memory of paralyze spell equipped, which has its own timer.

**Comment by coruja747** [comment]
Yes, but the memory item is always created with same timer as the field timer, and when the field got removed it also remove the memory on all chars stepping over it. Long story short: when the field disappear it also remove the memory on chars

So default internal behavior is working fine, probably it should be some custom script causing some conflict on this, or some kind of custom client that removed this "update packet" trying to save bandwidth

**Comment by Khaldor48** [comment]
Oh, you're right. I am sorry, just wanted to be helpful :-)
