### ISSUE TITLE
SQL do not work anymore since last Commit

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#224]
SQL do not work.... don't try this .f_add_rebuild...   Your console explode :-)

**Comment by Jhobean** [comment]
Any hint why last version don't work? If i can help just say where to look at.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/1996a214077cb4decbb35f2fb0c0a8ff43b7304a

**Comment by Jhobean** [comment]
Thx!
