### ISSUE TITLE
Taming skill open provocation target

### ISSUE THREAD

**Issue by FiLoUs64** [Sphereserver/Source#225]
When you start to tame an animal, a second target open for provocation.

Problem start in build 0.56.4.972

https://cdn.discordapp.com/attachments/637997956741464094/659784814685323264/Ultima_Online_-_Phil_MyShard_2019-12-26_10-48-34.mp4

**Comment by Nirad** [comment]
you can see the fix here
https://github.com/Nirad/Source/commit/dfca605232eba6c23e0cda026fd8024a9909cfcb

**Comment by coruja747** [comment]
Thanks, I merged it on source
Fixed https://github.com/Sphereserver/Source/commit/c9ac0efbb8a6a7ba49eccd8e5a4bfc352fd52c16

**Comment by Nirad** [comment]
Thx!
