### ISSUE TITLE
DUPE

### ISSUE THREAD

**Issue by Khaldor48** [Sphereserver/Source#227]
On Linux build (windows not tested) when I dupe some item, it gets property ARMOR from the Itemdef (of the baseid item!) instead of duplicating from targeted item.

 For example I have custom platemail armor chest which has armor 350,350 and is separately scripted. When I dupe this piece of armor I get duplicate but only ARMOR property has 30,30 (which is script armor value for regular iron platemail chest)

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/e227803ff8acc5ab085c6c7c045f7a5a3392d81f
