### ISSUE TITLE
Bank 

### ISSUE THREAD

**Issue by andremilgrau** [Sphereserver/Source#229]
After install last nightly vers to solve the problem that gm can't drop items inside players bankbox, now bankbox is working bad...

When the client is offline i see his bank, there is 4 containers. When the client log-on, i can see just 2 container (the client also...) 
Sometimes other containers appears. In the save file all this containers are liked with de bank box.

**Comment by coruja747** [comment]
Probably this should be bad network config blocking outgoing packets, try check your MaxPacketsPerTick / MaxSizePerTick settings on sphere.ini
