### ISSUE TITLE
New Sphere download links

### ISSUE THREAD

**Issue by coruja747** [Sphereserver/Source#231]
Hey Ben, can you update these links on Sphere download page plz?

- Changelog:
  - From: https://raw.githubusercontent.com/Sphereserver/Source/master/docs/REVISIONS-56-SERIES.TXT
  - To: https://raw.githubusercontent.com/Sphereserver/Source/master/changelog.txt

- VC Redistributable Package for Windows
  - From 2010: https://www.microsoft.com/en-us/download/details.aspx?id=5555
  - To 2015: https://support.microsoft.com/en-us/help/2977003/

- Added new 64bit builds (they are located on same path of 32bit builds)
  - Win: SphereSvr-Win64.zip
  - Linux: SphereSvr-Linux64.tar.gz

**Comment by Ben1028** [comment]
sure thing...    sorry didn't see this earlier.
