### ISSUE TITLE
Feature request - emotecolor

### ISSUE THREAD

**Issue by orishi** [Sphereserver/Source#232]
Hi, as much as I like <speechcolor> stored on characters, I would like to have <emotecolor> stored on characters - basically the color that the players set in for emote text in their client options.

**Comment by coruja747** [comment]
This client-side emote is just the default speech with * * around, the client send the same packet but using talkmode=2 (emote) instead talkmode=0 (say). So you can reproduce this same *emote* message on server-side using ```SAYUA colour, talkmode, font, lang_id, text``` with talkmode=2

But you're right, the default speech packet store the speech color on SPEECHCOLOR char property, but there's no EMOTECOLOR to store the emote color. This should be easy to do, I will take a look later

**Comment by orishi** [comment]
Yep, that's exactly what I need. Thank you.

**Comment by coruja747** [comment]
Implemented https://github.com/Sphereserver/Source/commit/5b29e68c2b58694c86bc181f62e9926606d0d2c7
