### ISSUE TITLE
Skill gain in minning don't seem to work

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#233]
I think this will fix. 
https://github.com/Sphereserver/Source/commit/2a24df642371b02ab0823f10cea95722b608522b

**Comment by coruja747** [comment]
It's working fine, mining skill only have skill gain when mining ores from ground

Smelting also requires mining to calculate the smelt success chance but this doesn't raise mining skill

**Comment by Jhobean** [comment]
Hoo. I tought mining was going up when smelting..  it was like this on 55i..  so we ajust this.   Because on 56, when smelting gain never go up. If its normal, ill close this issue.
