### ISSUE TITLE
Non static items disappears after logout/login

### ISSUE THREAD

**Issue by FiLoUs64** [Sphereserver/Source#234]
When you logout for example in front of a house and relog, you will not see the house. Same thing for doors and a lot of non static items.

Take a look at this video: https://cdn.discordapp.com/attachments/637997956741464094/670817973497495552/Ultima_Online_-_Phil_Cryptonite_2020-01-25_21-22-41.mp4

After moving and get the items out of the screen, it reappears.

Thanks

**Comment by coruja747** [comment]
This already got fixed some weeks ago, but it seems that you're using an custom sphere build, so you have to merge this fix into your code too

Honestly I don't remember the commit hash/date but it's working fine on latest build, so maybe rebasing your code to latest build should fix this

**Comment by FiLoUs64** [comment]
Thanks will check that

**Comment by FiLoUs64** [comment]
You're right. Thanks again.

**Comment by Nirad** [comment]
First why you Cole this one ?

**Comment by Nirad** [comment]
https://github.com/Sphereserver/Source/compare/master...Nirad:crypto-core?expand=1

**Comment by Nirad** [comment]
I mais something here ?
