### ISSUE TITLE
Item too heavy do not return to initial position

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#236]
When you try to add in your pack an item too Heavy. The  error message pop like normal But the item is teleport to 0,0,31

![image](https://user-images.githubusercontent.com/51728381/75632903-71459e80-5bce-11ea-9136-7413128b718b.png)

**Comment by Jhobean** [comment]
I tested many build and the bug begin in this build: 0.56.4.995

https://ci.appveyor.com/project/coruja747/source/builds/29978462/job/u8dcp76441pty0gs/artifacts

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/8ea4390a98114d276bf7d0842c73ba443d052d24
