### ISSUE TITLE
New feature of maxweight in the Backpack

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#238]
The feature do not work when you add item in a container in your backpack. So, you can put illimited qte of item in your backpack and walk slowly all the map with refresh potion.

![image](https://user-images.githubusercontent.com/51728381/76174529-30c1c400-617e-11ea-83eb-ada8e0d68bc5.png)

**Comment by Jhobean** [comment]
Second error on this system. If you put -1 in the ini for  unlimited. It's do not work anymore... Your max is 0

**Comment by coruja747** [comment]
Chars with GM=1 can always carry unlimited weight, the BackpackMaxWeight .ini setting only takes effect on players with GM=0, which seems to be working fine

But BackpackMaxWeight=-1 was really not working correctly so I already fixed it on latest build, try update to check if it's working fine

**Comment by Jhobean** [comment]
Thx. Work Well for the -1. But the weight in a sub container is not checked.  So if I have an i_bag in my backpack, I can drop illimited weight in it.

Second, it's possible to ajust the BackpackMaxWeight = maxweight?  So the BackpackMaxWeight will follow STR :-)

**Comment by Jhobean** [comment]
Work a+  Thx again
