### ISSUE TITLE
Hearall active do not work

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#239]
The commande .hearall do not work correctly.

I see the player emote and I do not see the player talking.

I see the NPC speech but not the player..

![image](https://user-images.githubusercontent.com/51728381/76710710-1f2d6e80-66e0-11ea-9a0d-c2915b37067b.png)

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/fcc1977c8fb775bb74438008d5c5a0bef9811dd8

**Comment by Jhobean** [comment]
Thx!
