### ISSUE TITLE
Weightreduction dont seem work correctly

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#240]
Nothing happen when I add item on this bag. I think it's suppos to reduce the weight.
I'm wrong?

```
[ITEMDEF i_xbag]
ID=i_bag
NAME=xbag
TYPE=t_container

on=@DropOn_Self
argo.weightreduction=50

on=@PickUp_Self
argo.weightreduction -=50
```

Maybe see this :  https://github.com/Sphereserver/Source-X/commit/76c9cdf488abce85b28fe5625c5d88e29e7ac130

**Comment by Jhobean** [comment]
I tested and I don't figure it out how is supose to work...

I set manualy  .xweightreduction 50 on a i_SAW put the saw in my bag and it's alway weight 6...   I think it's suppose to weight 3?

**Comment by coruja747** [comment]
Weight reduction can be used only on containers, eg: if you set WEIGHTREDUCTION=30 on the container, everything inside it will have -30% weight

**Comment by Jhobean** [comment]
:flushed: thx. But for information, on x it's in item.  I'll deal with that. Thx for the fix.
