### ISSUE TITLE
ON=@prestart Trigger seem to crash

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#241]
When I use ON=@prestart on a skill and put a return 1, all my skill are bloc for the ethernity :-)

![image](https://user-images.githubusercontent.com/51728381/77582372-a71c3100-6eb5-11ea-9c0f-9ceec9738c43.png)

Skill was item identification

**Comment by Khaldor48** [comment]
You must reset the action afterwards, e.g. 
on=@Prestart
action=-1
return 1

**Comment by Jhobean** [comment]
Thx
