### ISSUE TITLE
When skill pass in negative, Go up to 100.0

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#242]
We had an Issue where player has magery with the arrow DOWN.  When he raise an other skill magery  go down below 0.0 ->  -0.1.  We made a resync on the server and his skill climb to 100!

We saw a similar issue when the skill go highter than 200...  On the resync, the skill go to random between 0-100.

Any hints if it's script, core or client?  Thx

**Comment by Jhobean** [comment]
For the negative skill, i made these lines and it's work. Usefull to integrate in core? 

ON=@Skillchange //Use for avoiding to have negative skill
IF (<ARGN2> > 10000) // Go to negative -1 = 65526
 ARGN2=0
ENDIF

About the 200, not able to reproduce bit the bug occur sometime.

**Comment by coruja747** [comment]
Try using latest build, I added some security checks to prevent set negative value on skills

**Comment by Jhobean** [comment]
Work For the negative!  THX

**Comment by Jhobean** [comment]
Fix in: 1722fa94e18d1e970971c1c1d75c396164d1f3ee
