### ISSUE TITLE
Spell Fail and Reflect

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source#243]
When casting a spell on a player or npc, the spell applied by the opponent does not fail, and some spells are meaninglessly reflecting back the spell.  

e.g.
When I attack a dragon with magic or weapon, the dragon continues explosion or when a player throws a spell on me, the opponent's spell does not fail if I respond with spell.

**Comment by coruja747** [comment]
Try check if ```INTERRUPT=100.0,100.0``` is set correctly on all spells (sphere_spells.scp), this is the disturb change, so 0.0 means no chance of disturb and 100.0 means 100% chance of disturb

Also note that NPCs are not affected by disturb, so to make NPCs get disturbed when hit you must do it through scripts:
```
[EVENTS e_all_npcs]   // add this event to all NPCs setting EventsPet=e_all_npcs on sphere.ini
// Force NPC to fail/stop current action when it get hit
ON=@GetHit
ACTDIFF=-1
TIMER=0
```
