### ISSUE TITLE
MAXHits problem

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#249]
I explain the situation.

Wen I equip a special ITEM that it modify only the maxhits.

EX:
```
[ITEMDEF i_chainmail_coif_biro]
defname=i_chainmail_coif_biro
NAME=Coiffe de maille de Biro
ID=i_chainmail_coif
REQSTR=20
WEIGHT=7.0
ON=@EQUIP
SRC.MAXHITS=<SRC.MAXHITS>+2
```

It's fine. But now my STR and MAXHITS are unlink.  If I equip a second item boosting my STR, my hits do not move..

```
[ITEMDEF i_fou_chest]
ID=i_platemail_chest
TYPE=T_ARMOR
WEIGHT=23.0
ARMOR=115
REQSTR=60
NAME=Plastron du berseker

ON=@EQUIP
SRC.HITS=<SRC.HITS>+50
SRC.MODSTR=<SRC.MODSTR>+50
```

Any hint how to fix that?

**Comment by Jhobean** [comment]
Important add to this. When str and  maxhits are unlink, the spell do not affect anymore. Maxhits, maxstam and maxmana.....

**Comment by Jhobean** [comment]
On X, MODMAXHITS work  but on 56, no:

Just equip an unequip this item you'll understand

```
[ITEMDEF i_chainmail_coif_biro2] 
defname=i_chainmail_coif_biro
NAME=Coiffe de maille de Biro
ID=i_chainmail_coif
REQSTR=20
WEIGHT=7.0
ON=@EQUIP
SRC.modMAXHITS=<SRC.modMAXHITS>+2
ON=@UNEQUIP
SRC.modMAXHITS=<SRC.modMAXHITS>-2
```

**Comment by coruja747** [comment]
Changing HITS/STAM/MANA will call some security checks that will prevent the value exceed MAXHITS/MAXSTAM/MAXMANA value

To avoid this you must change the MOD* or MAX* value first, so you must replace
```
SRC.HITS += 50
SRC.MODSTR += 50
```
with
```
SRC.MODSTR += 50
SRC.HITS += 50
```
PS: also note that there's no MODMAXHITS on 56d, you must change MAXHITS directly

**Comment by Jhobean** [comment]
I already did your suggestion few week ago... That work for item equip but it break the link str / maxhits ..when the link is break, spell do not modify mana,stam,hits anymore...
