### ISSUE TITLE
BONUSHITS, BONUSSTAM, BONUSMANA

### ISSUE THREAD

**Issue by youhide** [Sphereserver/Source#25]
this item effect set a number much higher, i try to fix in CCharact here:

		short iHitpointIncrease = static_cast<short>(pItem->GetDefNum("BONUSHITS", true, true));
		if (iHitpointIncrease != 0)
			Stat_SetMax(STAT_STR, Stat_GetMax(STAT_STR) - iHitpointIncrease);

equip for iHitpointInscrease is short, and unequip is int.. but dont resolve nothing.

**Comment by Ben1028** [comment]
I haven't looked at the code in a while, but shouldn't this be 
```
short iHitpointIncrease = static_cast<short>(pItem->GetDefNum("BONUSHITS", true, true));
    if (iHitpointIncrease != 0)
        Stat_SetMax(STAT_STR, Stat_GetMax(STAT_STR) + iHitpointIncrease);
```
with a + iHitpointIncrease?

**Comment by youhide** [comment]
that have two methods, for equip "ItemEquip" and unequip "OnRemoveOb"

**Comment by coruja747** [comment]
what STR (char) and BONUSHITS (item) values are you using? I did some tests here with STR=100 + BONUSHITS=5 and it change correctly to 105

but anyway try using the nightly released today, I changed all these status related values from int to short

**Comment by youhide** [comment]
i got ur last commit and build again, its dont working.. can i doing something wrong? on ini do not have nothing who change that behavior all right? im testing with some artefact itens, try that @coruja747: 

[ITEMDEF i_holy_knights_breastplate]
ID=i_platemail_chest
NAME=Holy Knight's Breastplate
VALUE=5000
RESOURCES=i_relic_fragment
BonusHits=10
ReflectPhysicalDam=15
RESPHYSICAL=35
RESFIRE=3
RESCOLD=2
RESPOISON=3
RESENERGY=2
Rarity=1
TEVENTS=t_equipitem
CATEGORY=Artifacts
SUBSECTION=Gauntlet Artifacts
DESCRIPTION=Holy Knight's Breastplate
ON=@Create
   COLOR=0481
   ATTR=attr_magic|attr_identified
   HITPOINTS={90 120}

and personal thanks for answers !!

**Comment by nefthon** [comment]
Hmmm it may be too late to post here, but old 'items/sphere_items_typedef_equipitem.scp' had some of these props added on it's code because they were not hardcoded at all ... did you check inside it?
