### ISSUE TITLE
Weight penalty for running +N% of max carry weight

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#250]
I noticed 3 bug with this ini setting:
// Weight penalty for running +N% of max carry weight (0 = no effect)
RunningPenalty=10000

1- GM are affected with this
2- Changing the number in ini do almost nothing (at 100000 it begin to be interesting)
3- Do not affect when walking... Only running (Must be in walk too)

https://forum.spherecommunity.net/Thread-Question-about-weight-penalty?pid=29713#pid29713

**Comment by coruja747** [comment]
I'm doing some tests and it seems that both StaminaLossAtWeight and RunningPenalty are not working at all, the formula is really old and should be replaced

I already found the correct formula
```
if ( iWeight > iMaxWeight )
{
	int iWeightPenalty = 5 + ((iWeight - iMaxWeight) / 25);

	if ( IsStatFlag(STATF_OnHorse) )
		iWeightPenalty /= 3;

	if ( dir & DIR_MASK_RUNNING )
		iWeightPenalty *= 2;
}
```
This will consume 5 stam (+ 1 for each 25 extra weight), and the result can be reduced if char is mounted and doubled if running

Testing on real world usage on a mounted char with weight 408/407 I'm able to walk 100 tiles or run 50 tiles. But this is just 1 stone above the max weight, so its the minimum result. When more overweight it will drop stamina faster, eg: testing on mounted char with weight 791/407 I can only walk 17 tiles or run 9 tiles. So the results seems to be much better than old formula

But I'm trying to find a way to make this new formula customizable through StaminaLossAtWeight and RunningPenalty settings

**Comment by Jhobean** [comment]
Ok so when walking and running ratio is 2.   Interesting

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/191a13e7bc91a709db79d1270c467a5561038541

Changes are already commited but automatic CI compiler (appveyor) decided to skip this build, so there's no build to download yet. But next build will be compiled correctly

**Comment by Jhobean** [comment]
Hope next build will be soon.  Thx Coruja.  Fix  for GM too?
