### ISSUE TITLE
unhide Character when snooping

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#251]
If mu character is hide and snoop a back, my hide flag switch to off...

On the skill, I putted these line. 
```
ON=@prestart
if (<src.flags>&statf_hidden)
	serv.log hide
ELSE
	serv.log unhide
endif
```
On the prestart, my hide flag is already off
That show the unhiding action appear before the skill...  It seem that the dclic action unhide.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/22056643e50604d51baf8dfd554277f62eade499

PS: note that the default behavior for snooping skill is only have a chance to get revealed at failure, there's no reveal on success
