### ISSUE TITLE
<args> crash server

### ISSUE THREAD

**Issue by Skul83** [Sphereserver/Source#256]
These functions will crash the server when you use .crash

[function crash]
for 350
	if (strmatch(0,<local.crash>)) || (strmatch(00,<local.crash>))
		local.crash=1000 i_gold
	else
		local.crash=<local.crash>, 1000 i_gold
	endif
endfor
f_crash <local.crash>

[function f_crash]
if (<argv>)
	for x 0 <eval <argv> +-1>
		if (<isnum <strarg <argv[<local.x>]>>>)
			serv.newitem=<strarg <streat <argv[<local.x>]>>>
			new.amount=<strarg <argv[<local.x>]>>
			trysrc <uid> new.bounce
		else
			serv.newitem=<strarg <argv[<local.x>]>>
			trysrc <uid> new.bounce
		endif
	endfor
endif

as you can see <argv[349]> is too long and out of context somehow.  just a heads up.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/4390dc94beb1a9c7d82aabea3db457d3478eaba1
