### ISSUE TITLE
Spell duration varies between 32/64 bit versions

### ISSUE THREAD

**Issue by terrikate** [Sphereserver/Source#258]
What I have seen only affects the spells but I do not rule out affecting something else. In the 64-bit version, the duration is 10 times longer

Tested version https://ci.appveyor.com/project/coruja747/source/build/job/hbfqfu34wgfoap9p/artifacts

**Comment by coruja747** [comment]
I did some small changes on spell timers, try update to latest build to check if this still occur

**Comment by terrikate** [comment]
@coruja747 It works correctly in both versions. Thanks :)
