### ISSUE TITLE
AR value on shields does not increase after 100.0 parrying

### ISSUE THREAD

**Issue by slow-loki** [Sphereserver/Source#262]
If a player has 100.0 parrying or 500.00 parrying the total armour value will be the same.

For example, the shield has 100 Armour set in a scp

The player with 100.0 parrying equips it and gains +50 Armour.

If another player with 500.0 parrying the same shield gives +50 armour.

**Comment by coruja747** [comment]
I checked the code and it seems to be working fine, parrying is not used to calculate AR value, its only used to calculate the chance to parry (block) physical attacks

So wearing a shield while you have high parrying skill will not raise the shield AR but will make you block much more physical attacks

Parrying formula:
```
int iParryChance = 0;
if ( pCharTarg->IsStatFlag(STATF_HasShield) )	// parry using shield
{
	pItemHit = pCharTarg->LayerFind(LAYER_HAND2);
	iParryChance = pCharTarg->Skill_GetBase(SKILL_PARRYING) / 40;
}
else if ( pCharTarg->m_uidWeapon.IsItem() )	// parry using weapon
{
	pItemHit = pCharTarg->m_uidWeapon.ItemFind();
	iParryChance = pCharTarg->Skill_GetBase(SKILL_PARRYING) / 80;
}

if ( pCharTarg->Skill_GetBase(SKILL_PARRYING) >= 1000 )
	iParryChance += 5;

if ( pCharTarg->m_pPlayer )
{
	int iDex = pCharTarg->Stat_GetAdjusted(STAT_DEX);
	if ( iDex < 80 )
		iParryChance = iParryChance * (20 + iDex) / 100;
}
```
