### ISSUE TITLE
ERROR:Exception creating new memory block (CGrayMapBlock: Read)

### ISSUE THREAD

**Issue by ldilley** [Sphereserver/Source#264]
After creating a character and logging into the game, any movement attempt yields the following message within the `spheresvr` console:
```
13:05:ERROR:Exception creating new memory block at 4408,1168 (CGrayMapBlock: Read)
```

The above message is repeated for every movement attempt and the character remains in the same position where they spawned despite attempting to move. Relevant information is included below. Any assistance would be greatly appreciated.

**Sphere version:** 0.56d (latest master commit e01bb6f)
**Platform:** FreeBSD 12.2 (64 bit)
**Compiler:** Clang 10.0.1
**Client:** 7.0.90.16 (current)

**Comment by coruja747** [comment]
This error is triggered here: https://github.com/Sphereserver/Source/blob/b82fba7fcc1146dd2ff448af3c6b5c1fda49fcac/src/common/CSectorTemplate.cpp#L151
```
try
{
	pMapBlock = new CGrayMapBlock(ptBlock);
	ASSERT(pMapBlock);
}
catch ( const CGrayError &e )
{
	g_Log.EventError("Exception creating new memory block at %s (%s)\n", ptBlock.WriteUsed(), e.m_pszDescription);
	CurrentProfileData.Count(PROFILE_STAT_FAULTS, 1);
	return NULL;
}
```
It's working fine on windows, but I must take a look at linux builds

Probably the error occur when "new CGrayMapBlock(ptBlock)" is trying to allocate memory to create this new object, try check if your server have enough free RAM, or if sphere file have proper read/write access. But anyway, you can also try using older sphere builds to check if it's working fine, finding exactly the build version where this problem started will make it easy to fix on code

**Comment by ldilley** [comment]
This particular issue was related to `rctl` (resource control) limits imposed on the jail where Sphere was running. The jail still had ~400MB of physical memory available however, so I am surprised why the call to `new` returned `std::bad_alloc`. I'd assume that several hundred megabytes would be sufficient enough to allocate for a map block(?).

The ownership and permissions were all fine and it looks like the allocation code has not changed much since 2015 (b30d5e0) after reviewing the history. I'll close this issue considering that lifting resource caps and/or increasing memory resolved the issue. Thank you for the suggestions, @coruja747.
