### ISSUE TITLE
Specify a sphereserver licensing

### ISSUE THREAD

**Issue by lintax** [Sphereserver/Source#3]
We should choose from the following licenses
GPLv3
Apache 2.0
MIT

Please vote up for the one that is best. I personally back Apache as less restrictive, still a bit more protective than MIT is.

**Comment by denizsokmen** [comment]
Use GPLv3. For it can be forked and modified but developed proprietary which is harmful for the project, the forkers have to release their sources with GPLv3 (I don't know who obeys licences)

**Comment by lintax** [comment]
Many people do.
GPL makes impossible for some company to build a commercial product  based on a source, improve it, and provide a backports back. For such cases usually use either Apache license or LGPL (for example, wine / crossover pair)

**Comment by Ben1028** [comment]
I'll have to agree with Apache 2.0 license on this one.

**Comment by TorbenF** [comment]
MIT +1

**Comment by furio** [comment]
Go for Apache :)

**Comment by roberpot** [comment]
Apache license is a nice choice.

**Comment by lintax** [comment]
Ok, as for now, Apache got 4 votes, others - a single, thus applying an Apache 2.0 license
