### ISSUE TITLE
Script TRIGGER return value.

### ISSUE THREAD

**Issue by cbnolok** [Sphereserver/Source#30]
When you RETURN a value in a scripted trigger, you should be able to get that value with <Trigger @trig> but instead you get the TRIGRET_TYPE. Is there a reason to keep it as it is? It is more logical and useful to get the returned value.

**Comment by lintax** [comment]
How are you going to use this value in a scripted trigger?

**Comment by cbnolok** [comment]
I would use it this way:

ON=@UseTech
..
IF...
 RETURN 1
ELSE
 RETURN 0
ENDIF

//special abilities for a precise skillclass
[FUNCTION tech_warrior]
IF !<TRIGGER @UseTech>  //can i use an ability right now?
 RETURN 0
ENDIF

This is the most simple way, there obviously are many other. But i can't imagine the usefulness of having in a script a value which means "sphere parsed correctly the trigger", there are the errors in console to see if there's something wrong.

**Comment by lintax** [comment]
OK, this might been changed due to fact that this is a bit more simple straightforward rather the way I usually used. So no objections)

I used custom functions in this case and never used sphere skill system for my custom skills at all... moreover, even combat was absolutely scripted with almost no hardcoded code in action)

**Comment by coruja747** [comment]
here I'm using a similar method that works fine

ON=@Something
IF (...)
  return 1
ELSE
  return 0
ENDIF

[FUNCTION lol]
IF (<TRIGGER @Something>==1)
 return 1
ENDIF

**Comment by cbnolok** [comment]
Really? For me it returns always 2, which is TRIGRET_RET_DEFAULT.

**Comment by cbnolok** [comment]
This is not an issue anymore for the reason i shown here: https://github.com/Sphereserver/Source/pull/38.
