### ISSUE TITLE
Hue problems

### ISSUE THREAD

**Issue by coruja747** [Sphereserver/Source#43]
Is someone having problems with items inside containers that have color set but the client load it without any color? (this thing only happer on some random items, and not on all container items)

This thing is really strange, because it happen only on newest clients (using an old client like 5.0.2 it works fine), so probably OSI had changed some packets. But on the other hand, maybe it's not a packet change, because using an old sphere build from mid-2015 it works fine even using newest clients

so things are really confusing about this hue mistery, and if someone have any info or want help fix this thing, just comment here

**Comment by drk84** [comment]
Maybe it's related to the issue  that with clients  between 7.0.10.3 and 7.0.20.3 no items are displayed?

**Comment by coruja747** [comment]
this problem occour on client 7.0.49.2 using the packet do draw items inside containers, and that other problem occour on the packet to draw chars. But probably it's not the same problem but maybe the same fix could work for both, since both packets are used to load items but in different places

**Comment by coruja747** [comment]
@cbnolok just for curiousity, can you check if the runebook item 022c5 (8901) is showing the correct color when you change its color?

strangely the issue of this topic seems to happen ~only~ on this item, I have no idea why

**Comment by nefthon** [comment]
Have to say that a lot of people is complaining about this bug on IRC because they can't use builds newer than 28Jan (the newer nightly they have, but no one knows when exactly this problem started to appear) with 7.x-7.20 clients since they crash almost instantly. This looks to me more like a packet problem which may be caused not by packets themselves but some changes on CPointMap (since items equipped use p.z to store layer that may cause some issues), or other converted types or ... who knows exactly!

Just a note: This is not happening with latest uo clients so you can discard a packet change on 7.0.0.0+ clients and you may think about a problem for HS clients already using MULs instead of UOP (didn't confirm this, but no one using UOP Clients complained) and, since it worked before and it's working now... it's something on our side changed after Jan 28th.

**Comment by cbnolok** [comment]
I added the runebook on both EC (4.0.48.0) and CC (7.0.49.0), colored to 040, moved it around the pack and it's fine.

**Comment by coruja747** [comment]
probably this crash issue is an different problem, but also related to packets. I only have 2 UO installs (ML 5.0.0a~5.0.2d and TOL 7.0.44~7.0.49) so honestly I dont tested this crash issue yet, but i'll try to find an client 7.0.0~7.0.20 to test it

but about the hue problem, I tested on Sphere, RunUO, ServUO and AdaptUO and it doesn't work on all of them. So I think it's safe to don't consider it a problem, but "a lack of support of newest changes" lol. Unfortunately maybe the only way to fix it is logging on OSI to sniff packets (I don't have an OSI account :/) or using an UOP reader (does it really exists?) to check this item info

**Comment by coruja747** [comment]
bad news, my ML installation only support clients <= 5x and TOL installation only support clients >  7.0.45. HS/SA clients between 7.0.0~7.0.20 doesn't work on ML installation and also doesn't work on TOL installation. I'm trying to find a clean SA setup file but can't find it anywhere lol

anyway I'm checking for packet changes on network/send.cpp, maybe it could be the packet 0xF3 because its the only SA+ packet that was changed after 28/01/16. Try revert this packet using this code to check if it works

```
PacketItemWorldNew::PacketItemWorldNew(const CClient* target, CItem *item) : PacketItemWorld(XCMD_PutNew, 26, item->GetUID())
{
	ADDTOCALLSTACK("PacketItemWorldNew::PacketItemWorldNew");

	DataSource source = TileData;
	DWORD uid = item->GetUID();
	long amount = item->GetAmount();
	ITEMID_TYPE id = item->GetDispID();
	CPointMap p = item->GetTopPoint();
	DIR_TYPE dir = DIR_N;
	HUE_TYPE hue = item->GetHue();
	BYTE flags = 0;
	BYTE light = 0;

	adjustItemData(target, item, id, hue, amount, p, dir, flags, light);
	if (id == ITEMID_CORPSE)//dir is causing issues with corpse in this packet
		dir = DIR_N;

	if (id >= ITEMID_MULTI)
	{
		id = static_cast<ITEMID_TYPE>(id - ITEMID_MULTI);
		source = Multi;
	}
	else if (target->GetNetState()->isClientLessVersion(MINCLIVER_HS) && id >= ITEMID_MULTI_SA)
	{
		id = ITEMID_WorldGem;
	}

	writeInt16(1);
	writeByte(static_cast<BYTE>(source));// 0=tiledata,1=character,2=multi
	writeInt32(uid);
	writeInt16(static_cast<WORD>(id));
	writeByte(static_cast<BYTE>(dir));
	writeInt16(static_cast<WORD>(amount));
	writeInt16(static_cast<WORD>(amount));
	writeInt16(p.m_x);
	writeInt16(p.m_y);
	writeByte(p.m_z);
	writeByte(light);
	writeInt16(hue);
	writeByte(flags);

	if (target->GetNetState()->isClientVersion(MINCLIVER_HS))
		// 0 = World Item, 1 = Player Item ( ?? why should a item on the ground be defined as player item? and what is the difference? )
		writeInt16(0);
	
	trim();
	push(target);
}
```

**Comment by drk84** [comment]
If you need it, this is   an High sea Expansion installation https://www.dropbox.com/s/v33n5gmtah1dx0d/Ultima%20Online%207.0.20.0%20%28Original%29.rar?dl=0

**Comment by coruja747** [comment]
thx @drk84, with this HS installation (client 7.0.20.0) it really crash when I login. Probably it's an incompatibility with some packet, I will take a look here

**Comment by coruja747** [comment]
I found the problem, this client 7.0.20.0 is sending a weird crypt client version to sphere (something like 7.33.xx.xx), making sphere consider it a TOL client and send many unsupported packets, like the packet 0x78 where the server was sending the HS packet to this SA client, making it crash

but anyway I think the crash is fixed now

**Comment by drk84** [comment]
Seems fine with client 7.0.15.1 and 7.0.20.0, but with client 7.0.10.3 while you start to run / walk you get stuck after some steps. You can still use commands, talk or dismount from the mount. 
This is a link of 7.0.10.3 client if you need: 
https://www.dropbox.com/s/53gbhco011rp0il/client%207.0.10.3.exe?dl=0

**Comment by coruja747** [comment]
on some testing here I found something weird. SA+ clients have an new optional walk packet which is only used by clients if the server tell the client to use it. The setting to enable/disable this feature is the FEATURE_SA_MOVEMENT on sphere.ini

and strangely using client 7.0.10.3 (encrypted) it will always walk using this new packet even when FEATURE_SA_MOVEMENT is disabled, making the client get stuck because this walk packet is not enabled on server. And using this same 7.0.10.3 client but now selecting "remove encryption" feature on UOSteam it will use the old packet and will be able to walk perfectly

so maybe the best way to fix it is remove FEATURE_SA_MOVEMENT and make it permanently enabled on SA+ clients. But anyway while it's not fixed on source, you can fix it on your server just enabling FEATURE_SA_MOVEMENT on sphere.ini

**Comment by cbnolok** [comment]
I remember this packet having some problems when i tried it months ago,
like getting stuck as drk gets, so before enabling it forcefully i would
test extensively. For now the best thing imho would be to write a caveat in
sphere.ini.

**Comment by roberpot** [comment]
I'm not agree to remove the option on sphere.ini. Imho the better option is to add an explanation on sphere.ini with the listed versions that requires this option to be enabled. (cbnolok get out of my mind! :P)

**Comment by coruja747** [comment]
this packet problem only occour encrypted clients, and the others emulators like RunUO / ServUO / etc had automatically solved this problem not allowing encrypted clients to login on server. Since sphere allow encrypted clients to login, we must provide at least an minimum support to these clients, which unfortunately in this case they ~must~ use the new walk packet

I also doesn't need and doesnt use this packet, but I must admit that it doesn't make sense have an on/off switch to select between an walk packet and... another walk packet which does exactly the same thing

also doesn't make sense enable it only on encrypted clients and leave no-crypt clients using the old packet. And also doesn't make sense leave it broken intentionally and just add a warning on .ini saying "this doesn't work, but press this button to fix it"

so all possible solutions for this problem are crap. And choosing between many crap solutions, maybe the best fix is just leave everything as it is and recommend ppl to avoid use 7.0.0~7.0.10 encrypted clients, or use the no-crypt version of these clients

**Comment by cbnolok** [comment]
Agreed, this should be written on the .ini (a file that everyone should read)

**Comment by coruja747** [comment]
I found an working UOFiddler that can read .uop files and OSI really changed the runebook (item 8901) flags:
-pre HS: ArticleA, Container
-post HS: ArticleA, PartialHue, Container

so it's not an server problem, unfortunately there's nothing we can do about it

**Comment by nefthon** [comment]
Tried to reproduce it with 7.0.49.2: changing it's color to 0480 (default 'ice') results in success, doing the same with a halberd result in partial hue (maybe halberds had it since a long time? can't remember TBH), what I am missing?

**Comment by coruja747** [comment]
taking another look using UOFiddler after update UO to latest client patch 7.0.49.69, OSI had removed PartialHue flag from the runebook item (8901) and now it's working fine again

so the problem really was on UO files, and OSI already fixed it
