### ISSUE TITLE
Problem with BUFF/DEBUFF with strenght and maxhits.

### ISSUE THREAD

**Issue by Shamino-UO** [Sphereserver/Source#44]
Cunning/Feeblemind alters MODINT and MAXMANA.
Agility/Clumsy alters MODDEX and MAXSTAM.

**Strenght/Weaken alters MODDSTR but NOT MAXHITS. <--- This is the error.**

This same issue with Bless/Curse/Mass Curse.

MagicFlags=010|040|0400|0800

**Comment by coruja747** [comment]
it's working fine here, try set MAXHITS=0 before use MODSTR

this happen because if MAXHITS is set, the MODSTR will not override the MAXHITS value. So if you remove the MAXHITS value, the MODSTR will be able to increase/decrease the maxhits correctly. The same happen on all STR/DEX/INT stats

**Comment by Shamino-UO** [comment]
Ye is true, sorry hehe, closed issue.
