### ISSUE TITLE
Items tooltips don't show on disconnected players.

### ISSUE THREAD

**Issue by Shamino-UO** [Sphereserver/Source#49]
When mouse hover on items in backpack or bank in a disconnected player, they don't show any tooltip :/

Is an issue?

If not, how can force to show this tooltips?

**Comment by coruja747** [comment]
confirmed, tooltip doesn't open on logout players, including equipped items and also items inside backpack

I have no idea why, sphere seems to generate the tooltip but maybe something is preventing the server send the tooltip to client

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/43c45a00881b3595d0d4baa4e8891178c3e14475
