### ISSUE TITLE
MessageLoc

### ISSUE THREAD

**Issue by Kaylala** [Sphereserver/Source#50]
MessageLoc is not in CClient_Functions.tbl or CChar_Functions.tbl. Checking CChar.cpp and CClient.cpp shows it does not exist either. This was an addition a long time ago that has become missing. Ruining a lot of older scripts and new ones.

This also needs additions of EmoteLoc and SayLoc (SayLoc parsing arguments for 0x00 (Say), 0x08 Whisper, 0x09 yell). As most of sphere speech is actually in the clilocs and would clean out the use of parsing those resource consuming strings.

EmoteLoc also should be considered 0x02. 

All of the above are called in Packet C1. Providing a soft code fix is not going to be friendly with how much these get called in the game.

Replication will be easy using SysMessageLoc. Though EmoteLoc will take a bit more to parse and will need a nested EmoteLoc in it. One to parse to Parse to Src and one to Parse to Players around src.

**Comment by Kaylala** [comment]
C1 is the localizedMessage packet. It literally has all the code Packet 03 and AD do, but in localizations. It is like MessageLoc, MessageLocEx as it can parse colors and fonts. These should be added as well to stick with conformity.

MessageLoc, MsgL
MessageLocEx, MsgLEx
SayLoc
SayLocEx, SayLEx (Also takes whisper, yell, and normal say (Possibly guild and alliance).
EmoteLoc, EmoteL
EmoteLocEx, EmoteLEx

**Comment by Kaylala** [comment]
@coruja747 This could be a simple add, albeit the EmoteLoc. If you want, I can try and get VS back on this desktop, but I am sure you can do this with ease and little testing as the worst thing to process is the Emotes. MessageLoc and SayLoc should be priorities though (especially messageloc). Using SayLoc will free up a ton of resources from Say <String> and I can just add it all to the new Base Packs. 

Which is nice, because even all the combat says/messages are localized as well.

**Comment by Kaylala** [comment]
For overriding messages in sphere_msgs.scp (or other message functions such as SAY and MESSAGE) the
  syntax "@hue,font,3 clilocid,flags,affix[,arguments]" can be used, for example:
   "SAY @022,,3 1008097,01,MrSugarCube"

This actually is working. Xun and I are testing it now. But EmoteLoc is still an issue and needs hard code support. :)

We also are working on getting in Alliance and Guild in SysMessageLoc

**Comment by coruja747** [comment]
instead add new functions to every msg type, maybe it's better just use the @ formatting on current SAY / MESSAGE / SYSMESSAGE / EMOTE

eg:
SAY @,,0 Contemplating at the shrine has left you feeling more <ARGS>.
SAY @,,1 Contemplating at the shrine has left you feeling more <ARGS>.
SAY @,,2 1079546,<ARGS>

these 3 functions will return the same msg, changing only the msg type (0 = ASCII / 1 = unicode / 2 = cliloc), and also it's compatible with old 56b builds

**Comment by Kaylala** [comment]
We just have no coverage of it in Wiki, Revisions are limited to Cube cryptic notes... Wiki and Revisions contradict each other atm. Xun and I are working it out. Emote is not working right as it should. He added it to his indexes. We are writing quick softcode functions now to keep it all working as it was intended. :) Thanks Coruja though.

The issue is those modes. SayUA and MessageUO say color,talkmode,font, etc. But .... the way cube wrote it all is very different and works in different orders.

**Comment by Kaylala** [comment]
Also Cube noted 3 as cliloc, but Xun and I checked and it seems 2 is cliloc and 3 is clilocex

**Comment by Kaylala** [comment]
"For overriding messages in sphere_msgs.scp (or other message functions such as SAY and MESSAGE) the
  syntax "@hue,font,3 clilocid,flags,affix[,arguments]" can be used, for example:
   "SAY @022,,3 1008097,01,MrSugarCube"                           - Object says "MrSugarCube : poisoned you!" in red"

This is the Cube confusion atm.

**Comment by nefthon** [comment]
EMOTE can't be formatted, it may need some work to work with clilocs.
