### ISSUE TITLE
Multi Targeting Reticle

### ISSUE THREAD

**Issue by Kaylala** [Sphereserver/Source#51]
New changes in multis have made ships near impossible to place by default (Test with Gargoyle ship). Checks need to be done for Ships versus Housing. Other larger ships have slight issues with placement as well. Ships by EA standards I believe are centered, as sphere used to parse it.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/e46b5dc224274447d7f1c944a1e31d17e2a40163
