### ISSUE TITLE
VisualRange don't works after set higher than 18

### ISSUE THREAD

**Issue by GODEXTREME** [Sphereserver/Source#52]
When playing with VisualRange higher than 18, things still limited to 18.
Not sure if is clientside limited or something on sphere.

**Comment by coruja747** [comment]
classic clients have an client-side limit that only allow visual range between 5~18, setting any lower/higher value will make it not load objects correctly on screen. So sphere also prevent set values out of this 5~18 range to prevent weird client-side behavior

PS: on enhanced clients the max range is 31

**Comment by GODEXTREME** [comment]
Sad to hear that :(
I did test VisualRange lower than 5 and it did work!

**Comment by nefthon** [comment]
Did you test that Coruja? I did several checks on the firsts EC clients and 18-31 had no difference in the client.

**Comment by coruja747** [comment]
yep although it doesnt draw more objects on the extra range, if you set any higher unsupported value the range on client-side will fall to 0. But try using latest release, yesterday i did some changes on function addPlayerSee() that maybe will make this extra range work correctly

I cant remember exactly, but maybe the range values is 5-18 on classic clients and 1-31 on enhanced clients. But maybe setting < 5 on classic clients will work fine too
