### ISSUE TITLE
Travis-CI support

### ISSUE THREAD

**Issue by coruja747** [Sphereserver/Source#54]
@Ben1028 @TorbenF someone can set this AppVeyor hook on github settings plz?
I can't set it because I don't have owner access on the project :P

Honestly I don't know how it works, but maybe we just need to add this url: https://ci.appveyor.com/api/github/webhook?id=ylox4u925cs260v9

and select the "push" and "pull request" buttons as it show on this screen: https://programmaticponderings.files.wordpress.com/2014/05/github-to-appveyor-webhook-configuration.png

this will make the GitHub automatically connect to AppVeyor to instantly test all commits that we send to github

**Comment by coruja747** [comment]
nevermind, maybe it's better use Travis-CI instead AppVeyor

AppVeyor only test windows builds (using MSBuild), but Travis-CI can build both win/linux (using GCC). And it also have native support for GitHub <-> Travis-CI integration

all we need to do is sign in on Travis-CI (https://travis-ci.org/) using GitHub account (must be an project admin @Ben1028 @TorbenF) and click to add repository -> Sphereserver/Source

that's it, now all commits that we made to github now will make Travis-CI instantly test the build

PS: maybe the Travis-CI tests will fail at first moment because .travis.yml file should be set correctly to point proper project files to build (eg: /GraySvr.sln), but I can do this later

**Comment by coruja747** [comment]
anyone? :(

**Comment by Ben1028** [comment]
No need for this...   proper local testing is not that hard. Lets not add to everyone's laziness.

**Comment by coruja747** [comment]
That's exactly the point @Ben1028, sphere is multi-platform, and win (MSBuild) / linux (GCC) compilers are a bit different

sometimes we commit something tested and fully working on win, which will break the linux compiler (eg: MSBuild accept math/conversion between signed/unsigned values, but this will break GCC compiler)

here comes the Travis-CI, where even using MSBuild on local PC we can use Travis-CI to check if there's something wrong on GCC (also I don't know how it works, but Travis-CI can deploy the compiled SphereSvr.exe ~instantly~ to any external server using FTP, maybe this can be useful)

RunUO and POL also uses both AppVeyor and Travis-CI to test both win (AppVeyor) and linux (Travis-CI) builds at the same time, but I think only Travis-CI is enough

so it's up to you, but honestly I think it's a great tool and we can give it a try :smile:
