### ISSUE TITLE
Perma statf_war on NPCs

### ISSUE THREAD

**Issue by Shamino-UO** [Sphereserver/Source#55]
Last nightly have a bug with NPCs, when i hit a npc he put on war mode, but never never return to peace.

Prob the cause if this commit: https://github.com/Sphereserver/Source/commit/dd71ad7db306330aa3abe1498ea3e60db7fa061d

but i dont know.

**Comment by coruja747** [comment]
it occour only on human NPCs, monsters, or both?

**Comment by Shamino-UO** [comment]
Seems with both.

**Comment by nefthon** [comment]
fixed
