### ISSUE TITLE
REFx assigns HEX values to tag disregarding quote symbols. 

### ISSUE THREAD

**Issue by OTopCat** [Sphereserver/Source#56]
```
[plevel 1]
testt

[function testt]
ref3=<src>
ref3.tag.test1="1*12" <-this line will assign 0c to tag.test1 instead of string 1*12
tag.test2 "1*12"
say <tag.test1>
say <tag.test2>
```

**Comment by OTopCat** [comment]
works on 56c and 56d

**Comment by coruja747** [comment]
try using ""1*12""
I have no idea why, but sometimes the string is only stored as text when using double or triple ". It's just an minor issue, but anyway I will take a look when I get some free time

**Comment by OTopCat** [comment]
Any update? such a stupid bug. brakes almost all strings in tags =(

**Comment by cbnolok** [comment]
I can't check it now, but try to store the tag as "a 123" and then to
retrieve the value with STREAT

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/063dc07ddfd86dea2fa2fa470224771f44306ca6
