### ISSUE TITLE
56c changelog missing

### ISSUE THREAD

**Issue by coruja747** [Sphereserver/Source#58]
I don't know who have access to fix this, but 56c changelog is missing on the "revisions" page
http://prerelease.sphere.torfo.org/revisions.php

PS: 56c release date must be added on this page too (April 10 2016), and also 56b (Jun 16 2013)

**Comment by coruja747** [comment]
just a quick note, this text on nightly builds page must be also updated:
"This website contains experimental builds for SphereServer **0.56c**." -> **0.56d**
http://nightly.prerelease.sphere.torfo.org/

**Comment by Ben1028** [comment]
I will get to it...

**Comment by Ben1028** [comment]
Updated!
