### ISSUE TITLE
CRASH Spheresvr.exe with exception.

### ISSUE THREAD

**Issue by Shamino-UO** [Sphereserver/Source#59]
Hi, i have a server with 70-100 players, and have a very random .exe crash.

I mentioned it to Xun, but I put the last log before crash, help please, players will surely be lost if you do not find solution, I compile my own sphere, if I can help tell me something.

**The LOG:**

`12:10:WARNING:c9:Bad Login 14 (Another character on this account is already ingame)
12:10:ERROR:Timer expired without DECAY flag 'Pergamino de Portal Magico' (UID=040012a97)?
12:10:DEBUG:__ thread (2392) __ |  # | _____ function _____________ | ticks passed from previous function start ______
12:10:DEBUG:>>         2392     |  0 |               CWorld::OnTick | +0 
12:10:DEBUG:>>         2392     |  1 |              CSector::OnTick | +0 <-- exception catch point (below is guessed and could be incorrect!)
12:10:DEBUG:>>         2392     |  2 | IPHistoryManager::getHistoryForIP | +0 
12:10:CRITICAL:"Access Violation" (0x55252), in SUB: CSector::Sector::TickChar()
12:10:DEBUG:__ thread (2392) __ |  # | _____ function _____________ | ticks passed from previous function start ______
12:10:DEBUG:>>         2392     |  0 |               CWorld::OnTick | +0 
12:10:DEBUG:>>         2392     |  1 |              CSector::OnTick | +0 
12:10:DEBUG:>>         2392     |  2 |           CClient::r_LoadVal | +16 <-- exception catch point (below is guessed and could be incorrect!)
12:10:ERROR:Exception adding debug message on the exception.
12:10:DEBUG:char 0ecae48 ''
12:10:DEBUG:sector #1628 [5888,1024,0,0]
12:10:ERROR:Timer expired without DECAY flag 'Pergamino de Portal Magico' (UID=040012a99)?
12:10:ERROR:Timer expired without DECAY flag 'Pergamino de Portal Magico' (UID=040012aa5)?
12:10:DEBUG:__ thread (2392) __ |  # | _____ function _____________ | ticks passed from previous function start ______
12:10:DEBUG:>>         2392     |  0 |               CWorld::OnTick | +0 
12:10:DEBUG:>>         2392     |  1 |          CGObList::DeleteAll | +31 
12:10:DEBUG:>>         2392     |  2 |            CGObList::GetHead | +0 

CRASH HERE

Relaunch Sphere...
12:10:Sphere Version 0.56d-Release [WIN32] by www.spherecommunity.net, compiled at Apr 26 2016 (23:03:59) [build 1 / GIT hash 82e4e89]
12:10:Expansion maps supported: Felucca (0), Malas (3)
12:10:Allocating map sectors: 0=6144 3=1280`

This:
12:10:DEBUG:char 0ecae48 '' <--- .gouid and DONT EXIST now.
12:10:DEBUG:sector #1628 [5888,1024,0,0] <--- Is a dungeon, none rare here.

**Comment by coruja747** [comment]
Probably the error is on some function called when an client try to log-in on server.
Try using the default nightly build to check if it also have this problem, I'm using it here without any problems

also you can try enable map 2 and 4 on sphere.ini just to make sure, because sphere doesn't like to load objects on 'invalid' (null or not loaded) regions

**Comment by Shamino-UO** [comment]
coruja747 now only crash with this fail.

20:49:DEBUG:__ thread (2252) __ |  # | _____ function _____________ | ticks passed from previous function start ______
20:49:DEBUG:>>         2252     |  0 |               CWorld::OnTick | +0 
20:49:DEBUG:>>         2252     |  1 |              CSector::OnTick | +78 
20:49:DEBUG:>>         2252     |  2 |                CChar::OnTick | +0 <-- exception catch point (below is guessed and could be incorrect!)
20:49:DEBUG:>>         2252     |  3 |           CChar::OnTickEquip | +0 
20:49:DEBUG:>>         2252     |  4 | IPHistoryManager::getHistoryForIP | +0 
20:49:CRITICAL:"Access Violation" (0x55252), in SUB: CChar::Char::Ticking items()

**Comment by cbnolok** [comment]
Do you know since which build it began to happen? It really happens randomly or you do something that may trigger the exception? Is there a correlation with a client or char, first or not, log in? Is the last log you provided generated with a fully vanilla (standard) build (exe, ini, scripts)?

**Comment by coruja747** [comment]
try using latest 56d build / source code to check if it still happen, on past months I fixed some major bugs that are making spheresvr.exe crash
