### ISSUE TITLE
CMake as build environment

### ISSUE THREAD

**Issue by denizsokmen** [Sphereserver/Source#6]
CMake is a build tool to generate platform and compiler independent makefiles which makes things much easier to configure. It's extremely useful in large projects with dependencies.

**Comment by TorbenF** [comment]
We accept pull requests :) Just make sure to provide parameters for "prerelease" and "nightly".

**Comment by lintax** [comment]
seems it works ok, and perfecly parsed by CLion. are there any related tasks left?

**Comment by roberpot** [comment]
Cmake not generates the vs project. Xun has working on it.

**Comment by roberpot** [comment]
Updated CMake scripts. Now it works for CLion on windows too. If works for VS and linux, i think we can close this issue :-)
