### ISSUE TITLE
Party system error on console.

### ISSUE THREAD

**Issue by Shamino-UO** [Sphereserver/Source#60]
I have this error repeat alot of times on sphere console, seems if a fail on status update of party system.

I search revisions and found:
17-06-2015, Coruja
Fixed: Packet to update char hitpoints being sent twice to nearby party members.

06-08-2015, Coruja
Fixed: Client sending unnecessary mana/stam update to party members when opening the status menu.

31-01-2016, Coruja
Fixed: Character stats gump (hits/mana/stam) showing wrong info for players on same party.

The error:
00:26:DEBUG:__ thread (4764) __ |  # | _____ function _____________ | ticks passed from previous function start ______
00:26:DEBUG:>>         4764     |  0 |               CWorld::OnTick | +0 
00:26:DEBUG:>>         4764     |  1 |              CSector::OnTick | +157 
00:26:DEBUG:>>         4764     |  2 |                CChar::OnTick | +0 <-- exception catch point (below is guessed and could be incorrect!)
00:26:DEBUG:>>         4764     |  3 |    CChar::OnTickStatusUpdate | +0 
00:26:DEBUG:>>         4764     |  4 |         CClient::UpdateStats | +0 
00:26:DEBUG:>>         4764     |  5 |       CClient::addManaUpdate | +0 
00:26:DEBUG:>>         4764     |  6 |    CPartyDef::AddStatsUpdate | +0 
00:26:CRITICAL:"Access Violation" (0xf4b78), in CChar::Tick() #5 "update stats"

**Comment by coruja747** [comment]
are you using the latest 56c / 56d build? I already got this problem on my server and I did these changes just to fix it, since then I never got these "party exceptions" again

**Comment by Shamino-UO** [comment]
Ye i have 19 april build, can you copy and paste here the code fix for compare with my build? Only had this error with party.

**Comment by coruja747** [comment]
you already copy-pasted it :P
but anyway you can try some tweaks on this code, it's the function AddStatsUpdate() on CCparty.cpp. Try using this code to check if it will stop these console errors:

```
void CPartyDef::AddStatsUpdate( CChar *pChar, PacketSend *pPacket )
{
	ADDTOCALLSTACK("CPartyDef::AddStatsUpdate");
	size_t iQty = m_Chars.GetCharCount();
	if ( iQty <= 0 )
		return;

	CChar *pCharNow = NULL;
	CClient *pClient = NULL;
	for ( size_t i = 0; i < iQty; i++ )
	{
		pCharNow = m_Chars.GetChar(i).CharFind();
		if ( pCharNow && pCharNow != pChar )
		{
			pClient = pCharNow->GetClient();
			if ( pClient && pCharNow->CanSee(pChar) )
				pPacket->send(pClient);
		}
	}
}
```
