### ISSUE TITLE
Explosion potion dont work.

### ISSUE THREAD

**Issue by Shamino-UO** [Sphereserver/Source#61]
The explosion potion does not work, you can not throw, and explodes in character after 3 seconds, says "The target has moved," the last changes I see in the source code are these:

https://github.com/Sphereserver/Source/commit/34a2c9b3f52319c781e067eff050e02c82135948

Thanks.

**Comment by coruja747** [comment]
"The target has moved" is a target problem, not really a problem on explosion potions. Are you using any custom source code or custom script?

**Comment by Shamino-UO** [comment]
Xun have the same issue.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/5304d8e20ecdb8f5bd2b8efebc35d219d301fc37
