### ISSUE TITLE
Creating new char

### ISSUE THREAD

**Issue by azmanomer** [Sphereserver/Source#66]
When u creating new char some starting items not placing correctly and after save console removing them. For example if u give 5000gp to chars they take 4999gp and 1gp not placing world and after save server removing them.

**Comment by coruja747** [comment]
that's strange, it's working fine here
are you using latest sphere build with updated sphere_newb.scp?

**Comment by azmanomer** [comment]
yep its clean install but still taking 1gp lower and some items are missing.

**Comment by azmanomer** [comment]
i ll try with diffrent clients and reconfirm it.

**Comment by azmanomer** [comment]
http://nightly.prerelease.sphere.torfo.org/ latest 56c windows build.

**Comment by azmanomer** [comment]
yep i just tried with clean install sphere,scrpt pack and uo still same some items not placed correctly at char creation.

**Comment by coruja747** [comment]
I tried again here and it's working fine, what character name/profession/skills are you selecting?

**Comment by coruja747** [comment]
After some time I finally found an way to reproduce this bug, it happens only on some specific professions/skills trying to equip items that can't be equipped on char. But anyway, it's already fixed now
https://github.com/Sphereserver/Source/commit/47fccf5d34f60766266144b906fae1c43778ec92
