### ISSUE TITLE
Git services

### ISSUE THREAD

**Issue by Ben1028** [Sphereserver/Source#67]
If a service or webhook is needed, just give me the details and I can make it happen.
I see appveyor seems to be wanted for windows test and builds... Would we also need something else for linux? Travis CI possibly?

**Comment by coruja747** [comment]
thx for the help Ben :)
there's no service using both win/linux compiler at once, so we must use AppVeyor to test win builds and Travis-CI to test linux builds

I think both AppVeyor and Travis-CI can automatically set these github webhook settings, all you need to do is sign up on www.appveyor.com and www.travis-ci.org using your github account, click on "new project" and select Sphereserver/Source. This will automatically create the webhook settings here on github. After set webhooks properly, we must setup both AppVeyor / Travis-CI compiler variables to make everything work correctly. This can be done directly on both pages or adding .appveyor.yml and .travis.yml public files here on sphere source

I can send these files later, or if you prefer, just add me on admin group temporarily on Sphereserver project here on github and I can setup everything in a few minutes :P

**Comment by Ben1028** [comment]
Let me know know when you are done ;)

**Comment by coruja747** [comment]
okay, webhooks already created. Github now call AppVeyor / Travis-CI to test every commit

AppVeyor is already working fine, and Travis-CI just need some final polishment to make it compile the build properly. I'm going out for some hours now, but tonight I'm back to fix this thing :D

**Comment by coruja747** [comment]
Travis-CI integrations seems to be fine, it tries to compile every git commit using GCC but some makefile setting is breaking the compiler

can you provide these infos about the server building sphere nightlies plz?
-linux version
-compiler version
-file used to compile

maybe it will work better if we customize Travis-CI to use exactly this same environment

**Comment by Ben1028** [comment]
You need to install the mysql package

**Comment by coruja747** [comment]
I already tried all packages recommended on sphere readme
* libmysqld-dev
* libmysql++
* libmysql++-dev
* libmysqlclient-dev:i386

but the compiler continues not finding this lib: -I/usr/include/mysql -lmysqlclient

Travis-CI uses ubuntu 12.04.5 LTS precise + GCC 4.6.3, maybe on these versions this lib is installed on another path?

**Comment by Ben1028** [comment]
Using Linux mint 17 here (Linux ben-virtual-machine 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:08:14 UTC 2014 i686 athlon i686 GNU/Linux)
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by Ben1028** [comment]
I've done some test myself, but I can't get it to find libmysqlclient. Not sure what else to do from here.

**Comment by coruja747** [comment]
I also did some tests and.. nothing
ubuntu img used by Travis-CI already have many libs pre-installed but all of them are 64bit. If we try to compile something using 32bit it will require the 32bit version of many packages (mysql client, mysql server, mysql libs) and these packages will require even more packages (perl, perl libs, perl api, ...). And strangely some of these 32bits packages are not compatible with these others packages or doesn't even exist

I don't know if this is possible, but maybe we can workaround this creating another makefile to build sphere on 64bit compiler/libs. Maybe this won't cause any drawback, sphere nightlies will stay 32bit and this 64bit makefile will be used only on Travis-CI

**Comment by coruja747** [comment]
I removed the "-march=i686 -m32" line on makefile to let GCC use the default system architecture instead force the compiler to build on 32bit, and this finally fixed Travis-CI. It just need some tweaks to fix/hide some warnings related to 32-64bit conversion, but anyway, Travis-CI is now returning "success" instead "fail"

Can you check if this won't break the gcc on nightly builds?

**Comment by coruja747** [comment]
I fixed some more warnings and now both AppVeyor and Travis-CI seems to be running perfectly :D

**Comment by coruja747** [comment]
Thx for the help @Ben1028, AppVeyor and Travis-CI are running fine, so I think this issue can be marked as resolved

AppVeyor and Travis-CI are also ready to automatically build and export the win/linux builds to an external FTP, I sent the details on your PM on sphere forum
