### ISSUE TITLE
sigsegv - problems with memory

### ISSUE THREAD

**Issue by janinko** [Sphereserver/Source#68]
Hi,

I tried to move our server from 2009 version of sphere to the current version of sphere and encountered some sigsegv errors. I tried to debug it and ended up playing with Valgrind. I'll collect here some problems I found. Be aware that I haven't touched C++ in over 5 years so I'm quite rusty with it.

I'm on 64bit linux with 32bit compiled 1703a385b968a3194939f40700c78a12d7267ebb

**Comment by janinko** [comment]
[CResource.cpp#L2850](https://github.com/Sphereserver/Source/blob/1703a385b968a3194939f40700c78a12d7267ebb/src/graysvr/CResource.cpp#L2850)
```C++
			CRegionWorld * pRegion = new CRegionWorld( rid, pScript->GetArgStr());
			pNewDef = pRegion;
			ASSERT(pNewDef);
			pRegion->r_Load( *pScript );
			if ( ! pRegion->RealizeRegion() )
				delete pRegion; // might be a dupe ?
```
Here ``pRegion`` is created and assigned to ``pNewDef``. Then  ``pRegion`` is deleted, so ``pNewDef`` points to freed memory.
[CResource.cpp#L3194](https://github.com/Sphereserver/Source/blob/1703a385b968a3194939f40700c78a12d7267ebb/src/graysvr/CResource.cpp#L3194)
```C++
	if ( pNewLink )
	{
		pNewLink->SetResourceVar( pVarNum );

		// NOTE: we should not be linking to stuff in the *WORLD.SCP file.
		CResourceScript* pResScript = dynamic_cast <CResourceScript*>(pScript);
		if ( pResScript == NULL )	// can only link to it if it's a CResourceScript !
		{
			DEBUG_ERR(( "Can't link resources in the world save file\n" ));
			return( false );
		}
		// Now scan it for DEFNAME= or DEFNAME2= stuff ?
		pNewLink->SetLink(pResScript);
		pNewLink->ScanSection( restype );
	}
	else if ( pNewDef && pVarNum )
	{
		// Not linked but still may have a var name
		pNewDef->SetResourceVar( pVarNum );
	}
```
Here ``pNewDef`` (pointing to freed memory) is accesed.

**Comment by coruja747** [comment]
so maybe the best solution is call 'delete pRegion' + 'delete pNewDef' ?

**Comment by janinko** [comment]
Conditional jump or move depends on uninitialised value(s)
[CChar.cpp#L272](https://github.com/Sphereserver/Source/blob/1703a385b968a3194939f40700c78a12d7267ebb/src/graysvr/CChar.cpp#L272)
```C++
	size_t i = 0;
	for ( ; i < STAT_QTY; i++ )
	{
		Stat_SetBase(static_cast<STAT_TYPE>(i), 0);
		Stat_SetMod(static_cast<STAT_TYPE>(i), 0);
		Stat_SetVal(static_cast<STAT_TYPE>(i), 0);
		Stat_SetMax(static_cast<STAT_TYPE>(i), 0);
		m_Stat[i].m_regen = 0;
	}
```
Here in CCHar constructor, methods ``Stat_SetBase`` and ``Stat_SetMod`` depends on uninicialized struct ``m_Stat``

E.g:
[CCharSkill.cpp#L251 Stat_SetBase()](https://github.com/Sphereserver/Source/blob/1703a385b968a3194939f40700c78a12d7267ebb/src/graysvr/CCharSkill.cpp#L251)
```C++
	int iStatVal = Stat_GetBase(i);
	
(...)
	
	m_Stat[i].m_base = iVal;

	if ( i == STAT_STR && iVal < iStatVal )
```
``Stat_GetBase`` reads ``m_Stat[i].m_base`` that is uninitialized and store the uninitialized value to ``iStatVal`` that is used in the if statement.
