### ISSUE TITLE
Client Crash When Creating a New Character in Latest Client

### ISSUE THREAD

**Issue by HelenXLutja** [Sphereserver/Source#69]
Everything else works except for character creation. No errors show in the console and the client just becomes permanently unresponsive

**Comment by coruja747** [comment]
are you using classic or enhanced client?

**Comment by HelenXLutja** [comment]
classic client.  The problem seems to exist with all the 7.0 series clients that i have tried.  Using the XNA (the open source) client i can create characters and, wonderfully, almost everything from a players perspective appears to work in that so far. 

Switching to the nightly build did not solve the problem - it actually made it worse as now the XNA client will not create characters either. 

I was able to get character creation to work by switching down to a classic 6 series client.

**Comment by coruja747** [comment]
does it still occur? I think this problem got indirectly fixed when I fixed another bug where sphere was not getting the client version correctly during login proccess
