### ISSUE TITLE
Sphereserver.net Registration Page Broken

### ISSUE THREAD

**Issue by HelenXLutja** [Sphereserver/Source#71]
Does any here have a way to reach the owners of the web site as everything i have been trying (twitter,facebook,email) for a couple of weeks has been failing.  The registration page is broken because the captcha image section will not load and registration cannot be completed without it.

I've also been trying to find contact details for people that are active here to PM them but that has not been successful either. 

tried chrome,firefox, edge and IE.

Apologies in advance for a potentially off-topic issue.

**Comment by Ben1028** [comment]
The registration page is not broken. To display the re-captcha, you need to allow all web content to be displayed. For example, in IE, a message pops up at the bottom to ask if you want to display the non-secure content. Not sure if there is anything I can do to change that.

**Comment by HelenXLutja** [comment]
I got it to work only in internet explorer after noticing the secure content message.
