### ISSUE TITLE
Bug? DAM/ARMOR properties "dinamyically" set are not saved. 

### ISSUE THREAD

**Issue by drk84** [Sphereserver/Source#78]
If we set the DAM or ARMOR (for items) properties in game or by script (not in the chardef/itemdef block)  the values are accepted, but after saving, closing and restarting Sphere the ARMOR/DAM properties returns to their original values set in their Chardef/Itemdef
Example:
.xdam 30,40 on a npc 
save
restart sphere
NPC will get back their original values from the CharDef

I don't know if it's a bug or not.

**Comment by coruja747** [comment]
Fixed: https://github.com/Sphereserver/Source/commit/b63ff12841da1e2eb43f0780ee43390622e6b6ef
