### ISSUE TITLE
Unused files on project

### ISSUE THREAD

**Issue by roberpot** [Sphereserver/Source#8]
I found this files and i think can be removed:

common/CScriptCompiler.cpp
common/CScriptCompiler.h
common/CMapCache.cpp
common/CMapCache.h
common/twofish/Makefile

Can be removed?

**Comment by coruja747** [comment]
I tested it here and apparently these files can be removed without problems
/tables/CScriptCompiler.tbl can be removed too

PS: If removed, these files must be removed from GraySvr.vcxproj / GraySvr.vcxproj.filters too

**Comment by coruja747** [comment]
Files removed
https://github.com/Sphereserver/Source/commit/603f21fd8fc59291c5da12ca7b891f4c7042a439
