### ISSUE TITLE
Stealing Bug

### ISSUE THREAD

**Issue by drk84** [Sphereserver/Source#81]
When  you try to use the Stealing skill, you always get the message: "You can't steal from corpses". 
This happens when trying to steal an item (the targetted items doesn't have the newbie attribute) from both players or npcs.
Example:
Dclick on another player/npc backpack.
Use the stealing skill.
"You can't steal from corpses" message will appear.

**Comment by coruja747** [comment]
I fixed it some minutes ago, try using the latest nightly build to check if it's working fine now
https://github.com/Sphereserver/Source/commit/a208eb2c3eaee6033c1cb61464de2282fd29b975

**Comment by drk84** [comment]
Yes it seems to works fine, thanks
