### ISSUE TITLE
Feature: Allow NPCs to use bonus damage from bonusCombatStat/bonusCombatPercent and increasedam 

### ISSUE THREAD

**Issue by drk84** [Sphereserver/Source#85]
While it's possible to do that by using a formula in @hit, it will be nice to have an .ini setting that allow to take in consideration both bonusCombatStat/bonusCombatPercent and the increasedam property.

**Comment by coruja747** [comment]
this can be easily done on source code with an simple 0/1 boolean on sphere.ini, but there's an problem: sphere.ini already have too many settings and C++ code will return "too many variables" error if we add just a single variable

so to add this new setting, another old setting must be removed, and unfortunately at this moment I can't find any old setting that can be removed
