### ISSUE TITLE
Buying pets from npcs  with followers limit reached

### ISSUE THREAD

**Issue by s0ckz** [Sphereserver/Source#86]
If OF_PetSlot is enabled and a player has like 1 follower (max 1 also), when it's tried to buy a new pet from NPC, the message that you can't have more followers is shown but the gold is also taken from the char.

I found out that the error is here: https://github.com/Sphereserver/Source/blob/master/src/graysvr/CClientEvent.cpp#L949

I guess the ID returned is not valid, so I verified that Use_Figurine function has a similar call and, when id is not valid, there's another try using another function. The code that I wrote (and works is):

```
		if ( IsSetOF(OF_PetSlots) )
		{
			CREID_TYPE id = pItem->m_itFigurine.m_ID;
			if ( !id )
			{
				id = CItemBase::FindCharTrack(pItem->GetID());
			}

			CCharBase *pPetDef = CCharBase::FindCharBase(id);
			if ( pPetDef )
			{
				if ( !m_pChar->FollowersUpdate(pVendor, static_cast<short>(maximum(1, pPetDef->GetDefNum("FOLLOWERSLOTS"))), true) )
				{
					m_pChar->SysMessageDefault(DEFMSG_PETSLOTS_TRY_CONTROL);
					return;
				}
			}
		}
```

Note that another bug is found here... The FollowersUpdate function is called without passing the third parameter, specifying that it's a test only. So, a player would have 2 * FollowerSlots summed to his CurFollower field.

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/8e2de0e20581f1c92d7f12e0d45a96129a533bb0
