### ISSUE TITLE
Bug: Error in actdiff value when fighting when CombatHitChanceEra is different from 0.

### ISSUE THREAD

**Issue by drk84** [Sphereserver/Source#88]
When CombatHitChanceEra is set to 1 or 2, the actdiff value is the result of a comparison of the current Attacker Weapon skill and the Defender weapon skill that the Attacker is currently using. 

In few words, if the attacker is using swordsmanship the actdiff value will be based on the Swordsmanship skills of both characters, no matter what weapons (or wrestling) the defender is actually using.

Example:
Player A (swordsmanship 100.0) attacks an unarmed NPC (wrestling).
The Actdiff of the fighting action is based on the Player A Swordmanship and the NPC Swordsmanship (instead of wrestling)

If i am correct the  ACTDIFF value should be  influenced by the defender current weapon (or wrestling) skill value.

I hope i explained it well :p

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/0341418513bfcf7cbe60b017b31d283c5167ab9c
