### ISSUE TITLE
InitHiddenSkills problem

### ISSUE THREAD

**Issue by coruja747** [Sphereserver/Source#9]
InitHiddenSkills on sphere.ini is used when the player create a new char, to add initial skills values even on skills that this client can't see

but I think it's wrong, we must set char skills based on server settings (if the skill is enabled/disabled on server) and not just checking for the client version

eg: the server client is 6.x.x.x but someone create an account and do the first login using client 4.x.x, this char will be created with 0.0 on all SE / ML / SA skills just because the player created the char using an old client

so I think InitHiddenSkills feature can be removed, because it doesn't work well and can cause some problems like this. I'm opening this issue to vote, if everyone agree I can remove it

**Comment by lintax** [comment]
Imagine if I change this INI setting several times during server lifetime?
If server admin will update his server to allow new skills, all characters initialized will have zeroes here.

The correct solution as for me should be:
1. Keep target client version (upper limit) in save file
2. Always init all skills regardless of the state of current client or server configuration
3. Loading older save with newer target version configuration should update skills for characters

**Comment by coruja747** [comment]
these skills are already handled by .ini settings like FEATURE_SE_NINJASAM, FEATURE_ML_UPDATE, etc. So if someone want these skills, just enable these settings. Of if doesn't want it anymore, just disable it and these skills won't be set on character creation anymore

but honestly I think we doesn't really need store client version in case of settings changes. If the server admin decide to change the server expansion from ML to HS (example), it's better let him decide what he will do with old accounts :P (new skills can be easily set on all accounts with a simple ~5 lines softcoded function, or even not set)

**Comment by lintax** [comment]
Character conversion due to some external changes is usually a pain for admin. Of course, he can script, but as a fact we lose only a little bit if storing the skills on characters, so why not storing them and leaving less problems to admin?)

**Comment by Ben1028** [comment]
changes have been done already...  closing this
