### ISSUE TITLE
DeadCannotSeeLiving=2 cannot see gm=1

### ISSUE THREAD

**Issue by MariusVendetta** [Sphereserver/Source#99]
Setting in sphere.ini
// Ghosts are not able to see and hear living players and creatures (0=disabled, 1=only npcs, 2=both npcs and players)
DeadCannotSeeLiving=2

cannot see the game masters if dead.

**Comment by MariusVendetta** [comment]
maybe ccharstatus at line 829

if ( iDeadCannotSee == 2 )
to
if ( ( iDeadCannotSee == 2 ) && !IsPriv(PRIV_GM) )

right?

**Comment by MariusVendetta** [comment]
i finally succeeded on building sphere on windows.

the right correction is:
if ( (iDeadCannotSee == 2) && !pChar->IsPriv(PRIV_GM) )

and it works

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/a1aea090ac6cc1fa330cf1ebfbf709fbf4d07d66
